/**
 * Plantéis REAIS do Mundial 2026 (convocatórias FIFA).
 * GERADO por scripts/gen_squads.py a partir de
 * data/convocados_mundial_2026.csv — NÃO editar à mão.
 * Posições atribuídas pela ordem da lista (GR→DEF→MED→AVA), indicativas.
 */
import type { Footballer, Pos } from './types';

function pl(team: string, name: string, pos: Pos, number: number): Footballer {
  return { id: `${team}-${number}`, name, team, pos, number };
}

export const EXTRA_SQUADS: Record<string, Footballer[]> = {
  RSA: [
    pl('RSA', "Ronwen Williams", 'GR', 1),
    pl('RSA', "Ricardo Goss", 'GR', 2),
    pl('RSA', "Sipho Chaine", 'GR', 3),
    pl('RSA', "Khuliso Mudau", 'DEF', 4),
    pl('RSA', "Nkosinathi Sibisi", 'DEF', 5),
    pl('RSA', "Ime Okon", 'DEF', 6),
    pl('RSA', "Khulumani Ndamane", 'DEF', 7),
    pl('RSA', "Aubrey Modiba", 'DEF', 8),
    pl('RSA', "Samukelo Kabini", 'DEF', 9),
    pl('RSA', "Thabang Matuludi", 'DEF', 10),
    pl('RSA', "Olwethu Makhanya", 'DEF', 11),
    pl('RSA', "Kamogelo Sebelebele", 'MED', 12),
    pl('RSA', "Bradley Cross", 'MED', 13),
    pl('RSA', "Mbekezeli Mbokazi", 'MED', 14),
    pl('RSA', "Teboho Mokoena", 'MED', 15),
    pl('RSA', "Thalente Mbatha", 'MED', 16),
    pl('RSA', "Sphephelo Sithole", 'MED', 17),
    pl('RSA', "Jayden Adams", 'MED', 18),
    pl('RSA', "Oswin Appollis", 'MED', 19),
    pl('RSA', "Iqraam Rayners", 'AVA', 20),
    pl('RSA', "Tshepang Moremi", 'AVA', 21),
    pl('RSA', "Relebohile Mofokeng", 'AVA', 22),
    pl('RSA', "Evidence Makgopa", 'AVA', 23),
    pl('RSA', "Themba Zwane", 'AVA', 24),
    pl('RSA', "Lyle Foster", 'AVA', 25),
    pl('RSA', "Thapelo Maseko", 'AVA', 26),
  ],
  GER: [
    pl('GER', "Oliver Baumann", 'GR', 1),
    pl('GER', "Manuel Neuer", 'GR', 2),
    pl('GER', "Alexander Nubel", 'GR', 3),
    pl('GER', "Waldemar Anton", 'DEF', 4),
    pl('GER', "Nathaniel Brown", 'DEF', 5),
    pl('GER', "Pascal Gross", 'DEF', 6),
    pl('GER', "Joshua Kimmich", 'DEF', 7),
    pl('GER', "Felix Nmecha", 'DEF', 8),
    pl('GER', "Aleksandar Pavlovic", 'DEF', 9),
    pl('GER', "David Raum", 'DEF', 10),
    pl('GER', "Antonio Rudiger", 'DEF', 11),
    pl('GER', "Nico Schlotterbeck", 'MED', 12),
    pl('GER', "Angelo Stiller", 'MED', 13),
    pl('GER', "Jonathan Tah", 'MED', 14),
    pl('GER', "Malick Thiaw", 'MED', 15),
    pl('GER', "Assan Ouédraogo", 'MED', 16),
    pl('GER', "Nadiem Amiri", 'MED', 17),
    pl('GER', "Maximilian Beier", 'MED', 18),
    pl('GER', "Leon Goretzka", 'MED', 19),
    pl('GER', "Kai Havertz", 'AVA', 20),
    pl('GER', "Jamie Leweling", 'AVA', 21),
    pl('GER', "Jamal Musiala", 'AVA', 22),
    pl('GER', "Leroy Sané", 'AVA', 23),
    pl('GER', "Deniz Undav", 'AVA', 24),
    pl('GER', "Florian Wirtz", 'AVA', 25),
    pl('GER', "Nick Woltemade", 'AVA', 26),
  ],
  KSA: [
    pl('KSA', "Ahmed Al Kassar", 'GR', 1),
    pl('KSA', "Mohammed Al Owais", 'GR', 2),
    pl('KSA', "Nawaf Al Aqidi", 'GR', 3),
    pl('KSA', "Saud Abdulhamid", 'DEF', 4),
    pl('KSA', "Mohammed Abu Al Shamat", 'DEF', 5),
    pl('KSA', "Khalid Al Ghannam", 'DEF', 6),
    pl('KSA', "Moteb Al Harbi", 'DEF', 7),
    pl('KSA', "Abdulelah Al Amri", 'DEF', 8),
    pl('KSA', "Nawaf Boushal", 'DEF', 9),
    pl('KSA', "Hassan Kadesh", 'DEF', 10),
    pl('KSA', "Ali Lajami", 'DEF', 11),
    pl('KSA', "Ali Majrashi", 'MED', 12),
    pl('KSA', "Hassan Tambakti", 'MED', 13),
    pl('KSA', "Jehad Thikri", 'MED', 14),
    pl('KSA', "Nasser Al Dawsari", 'MED', 15),
    pl('KSA', "Alaa Al Hajji", 'MED', 16),
    pl('KSA', "Ziyad Al Johani", 'MED', 17),
    pl('KSA', "Musab Al Juwayr", 'MED', 18),
    pl('KSA', "Abdullah Al Khaibari", 'MED', 19),
    pl('KSA', "Mohammed Kanno", 'AVA', 20),
    pl('KSA', "Sultan Mandash", 'AVA', 21),
    pl('KSA', "Ayman Yahya", 'AVA', 22),
    pl('KSA', "Feras Al Brikan", 'AVA', 23),
    pl('KSA', "Salem Al Dawsari", 'AVA', 24),
    pl('KSA', "Abdullah Al Hamdan", 'AVA', 25),
    pl('KSA', "Saleh Al Shehri", 'AVA', 26),
  ],
  ALG: [
    pl('ALG', "Luca Zidane", 'GR', 1),
    pl('ALG', "Oussama Benbot", 'GR', 2),
    pl('ALG', "Melvin Mastil", 'GR', 3),
    pl('ALG', "Abdelatif Ramdane", 'DEF', 4),
    pl('ALG', "Rafik Belghali", 'DEF', 5),
    pl('ALG', "Samir Chergui", 'DEF', 6),
    pl('ALG', "Rayan Ait-Nouri", 'DEF', 7),
    pl('ALG', "Jaouen Hadjam", 'DEF', 8),
    pl('ALG', "Aissa Mandi", 'DEF', 9),
    pl('ALG', "Ramy Bensebaini", 'DEF', 10),
    pl('ALG', "Zineddine Belaid", 'DEF', 11),
    pl('ALG', "Achref Abada", 'MED', 12),
    pl('ALG', "Mohamed Amine Tougai", 'MED', 13),
    pl('ALG', "Nabil Bentaleb", 'MED', 14),
    pl('ALG', "Hicham Boudaqui", 'MED', 15),
    pl('ALG', "Houssem Aouar", 'MED', 16),
    pl('ALG', "Farès Chaibi", 'MED', 17),
    pl('ALG', "Ibrahim Maza", 'MED', 18),
    pl('ALG', "Yacine Titraoui", 'MED', 19),
    pl('ALG', "Ramiz Zerrouki", 'AVA', 20),
    pl('ALG', "Mohamed Amine Amoura", 'AVA', 21),
    pl('ALG', "Nadhir Benbouali", 'AVA', 22),
    pl('ALG', "Adil Boulbina", 'AVA', 23),
    pl('ALG', "Farès Ghedjemis", 'AVA', 24),
    pl('ALG', "Amine Gouri", 'AVA', 25),
    pl('ALG', "Anis Hadj Moussa", 'AVA', 26),
    pl('ALG', "Riyad Mahrez", 'AVA', 27),
  ],
  ARG: [
    pl('ARG', "Emiliano Martínez", 'GR', 1),
    pl('ARG', "Gerónimo Rulli", 'GR', 2),
    pl('ARG', "Juan Musso", 'GR', 3),
    pl('ARG', "Nahuel Molina", 'DEF', 4),
    pl('ARG', "Gonzalo Montiel", 'DEF', 5),
    pl('ARG', "Cuti Romero", 'DEF', 6),
    pl('ARG', "Otamendi", 'DEF', 7),
    pl('ARG', "Lisandro Martínez", 'DEF', 8),
    pl('ARG', "Marcos Senesi", 'DEF', 9),
    pl('ARG', "Nicolás Tagliafico", 'DEF', 10),
    pl('ARG', "Facundo Medina", 'DEF', 11),
    pl('ARG', "De Paul", 'MED', 12),
    pl('ARG', "Enzo Fernández", 'MED', 13),
    pl('ARG', "Paredes", 'MED', 14),
    pl('ARG', "Mac Allister", 'MED', 15),
    pl('ARG', "Valentín Barco", 'MED', 16),
    pl('ARG', "Lo Celso", 'MED', 17),
    pl('ARG', "Exequiel Palacios", 'MED', 18),
    pl('ARG', "Thiago Almada", 'MED', 19),
    pl('ARG', "Nico Paz", 'AVA', 20),
    pl('ARG', "Lionel Messi", 'AVA', 21),
    pl('ARG', "Nico González", 'AVA', 22),
    pl('ARG', "Giuliano Simeone", 'AVA', 23),
    pl('ARG', "Flaco Lopez", 'AVA', 24),
    pl('ARG', "Julián Álvarez", 'AVA', 25),
    pl('ARG', "Lautaro Martínez", 'AVA', 26),
  ],
  AUS: [
    pl('AUS', "Patrick Beach", 'GR', 1),
    pl('AUS', "Paul Izzo", 'GR', 2),
    pl('AUS', "Maty Ryan", 'GR', 3),
    pl('AUS', "Aziz Behich", 'DEF', 4),
    pl('AUS', "Jordan Bos", 'DEF', 5),
    pl('AUS', "Cameron Burgess", 'DEF', 6),
    pl('AUS', "Alessandro Circati", 'DEF', 7),
    pl('AUS', "Milos Degenek", 'DEF', 8),
    pl('AUS', "Jason Geria", 'DEF', 9),
    pl('AUS', "Lucas Herrington", 'DEF', 10),
    pl('AUS', "Jacob Italiano", 'DEF', 11),
    pl('AUS', "Harry Souttar", 'MED', 12),
    pl('AUS', "Kai Trewin", 'MED', 13),
    pl('AUS', "Cameron Devlin", 'MED', 14),
    pl('AUS', "Ajdin Hrustic", 'MED', 15),
    pl('AUS', "Jackson Irvine", 'MED', 16),
    pl('AUS', "Connor Metcalfe", 'MED', 17),
    pl('AUS', "Paul Okon-Engstler", 'MED', 18),
    pl('AUS', "Aiden O'Neill", 'MED', 19),
    pl('AUS', "Nestory Irankunda", 'AVA', 20),
    pl('AUS', "Mathew Leckie", 'AVA', 21),
    pl('AUS', "Awer Mabil", 'AVA', 22),
    pl('AUS', "Mohamed Toure", 'AVA', 23),
    pl('AUS', "Nishan Velupillay", 'AVA', 24),
    pl('AUS', "Cristian Volpato", 'AVA', 25),
    pl('AUS', "Tete Yengi", 'AVA', 26),
  ],
  AUT: [
    pl('AUT', "Alexander Schlager", 'GR', 1),
    pl('AUT', "Florian Wiegele", 'GR', 2),
    pl('AUT', "Patrick Pentz", 'GR', 3),
    pl('AUT', "David Affengruber", 'DEF', 4),
    pl('AUT', "Kevin Danso", 'DEF', 5),
    pl('AUT', "Stefan Posch", 'DEF', 6),
    pl('AUT', "David Alaba", 'DEF', 7),
    pl('AUT', "Philipp Lienhart", 'DEF', 8),
    pl('AUT', "Phillipp Mwene", 'DEF', 9),
    pl('AUT', "Alexander Prass", 'DEF', 10),
    pl('AUT', "Marco Friedl", 'DEF', 11),
    pl('AUT', "Michael Svoboda", 'MED', 12),
    pl('AUT', "Xaver Schlager", 'MED', 13),
    pl('AUT', "Nicolas Seiwald", 'MED', 14),
    pl('AUT', "Marcel Sabitzer", 'MED', 15),
    pl('AUT', "Florian Grillitsch", 'MED', 16),
    pl('AUT', "Carney Chukwuemeka", 'MED', 17),
    pl('AUT', "Romano Schmid", 'MED', 18),
    pl('AUT', "Ljubicic", 'MED', 19),
    pl('AUT', "Konrad Laimer", 'AVA', 20),
    pl('AUT', "Patrick Wimmer", 'AVA', 21),
    pl('AUT', "Paul Wanner", 'AVA', 22),
    pl('AUT', "Alessandro Schopf", 'AVA', 23),
    pl('AUT', "Marko Arnautović", 'AVA', 24),
    pl('AUT', "Michael Gregoritsch", 'AVA', 25),
    pl('AUT', "Sasa Kalajdzic", 'AVA', 26),
  ],
  BEL: [
    pl('BEL', "Courtois", 'GR', 1),
    pl('BEL', "Lammens", 'GR', 2),
    pl('BEL', "Mike Penders", 'GR', 3),
    pl('BEL', "Timothy Castagne", 'DEF', 4),
    pl('BEL', "Zeno Debast", 'DEF', 5),
    pl('BEL', "Koni De Winter", 'DEF', 6),
    pl('BEL', "Brandon Mechele", 'DEF', 7),
    pl('BEL', "Arthur Theate", 'DEF', 8),
    pl('BEL', "Maxim De Cuyper", 'DEF', 9),
    pl('BEL', "Thomas Meunier", 'DEF', 10),
    pl('BEL', "Nathan Ngoy", 'DEF', 11),
    pl('BEL', "Joaquin Seys", 'MED', 12),
    pl('BEL', "Kevin De Bruyne", 'MED', 13),
    pl('BEL', "Amadou Onana", 'MED', 14),
    pl('BEL', "Nicolas Raskin", 'MED', 15),
    pl('BEL', "Youri Tielemans", 'MED', 16),
    pl('BEL', "Hans Vanaken", 'MED', 17),
    pl('BEL', "Axel Witsel", 'MED', 18),
    pl('BEL', "Charles De Ketelaere", 'MED', 19),
    pl('BEL', "Mathias Fernandez-Pardo", 'AVA', 20),
    pl('BEL', "Jeremy Doku", 'AVA', 21),
    pl('BEL', "Romelu Lukaku", 'AVA', 22),
    pl('BEL', "Alexis Saelemaekers", 'AVA', 23),
    pl('BEL', "Leandro Trossard", 'AVA', 24),
    pl('BEL', "Dodi Lukebakio", 'AVA', 25),
    pl('BEL', "Diego Moreira", 'AVA', 26),
  ],
  BIH: [
    pl('BIH', "Nikola Vasilj", 'GR', 1),
    pl('BIH', "Martin Zlomislic", 'GR', 2),
    pl('BIH', "Mladen Jurkas", 'GR', 3),
    pl('BIH', "Sead Kolasinac", 'DEF', 4),
    pl('BIH', "Amar Dedic", 'DEF', 5),
    pl('BIH', "Nihad Mujakic", 'DEF', 6),
    pl('BIH', "Nikola Katic", 'DEF', 7),
    pl('BIH', "Tarik Muharemovic", 'DEF', 8),
    pl('BIH', "Stjepan Radeljic", 'DEF', 9),
    pl('BIH', "Dennis Hadzikadunic", 'DEF', 10),
    pl('BIH', "Arjan Malić", 'DEF', 11),
    pl('BIH', "Amir Hadziahmetovic", 'MED', 12),
    pl('BIH', "Ivan Sunjic", 'MED', 13),
    pl('BIH', "Ivan Basic", 'MED', 14),
    pl('BIH', "Dzenis Burnic", 'MED', 15),
    pl('BIH', "Benjamin Tahirovic", 'MED', 16),
    pl('BIH', "Amar Memic", 'MED', 17),
    pl('BIH', "Armin Gigovic", 'MED', 18),
    pl('BIH', "Kerim Alajbegovic", 'MED', 19),
    pl('BIH', "Esmir Bajraktarevic", 'AVA', 20),
    pl('BIH', "Ermin Mahmic", 'AVA', 21),
    pl('BIH', "Ermedin Demirovic", 'AVA', 22),
    pl('BIH', "Jovo Lukic", 'AVA', 23),
    pl('BIH', "Samed Bazdar", 'AVA', 24),
    pl('BIH', "Haris Tabakovic", 'AVA', 25),
    pl('BIH', "Edin Dzeko", 'AVA', 26),
  ],
  BRA: [
    pl('BRA', "Alisson", 'GR', 1),
    pl('BRA', "Ederson", 'GR', 2),
    pl('BRA', "Weverton", 'GR', 3),
    pl('BRA', "Alex Sandro", 'DEF', 4),
    pl('BRA', "Bremer", 'DEF', 5),
    pl('BRA', "Danilo", 'DEF', 6),
    pl('BRA', "Douglas Santos", 'DEF', 7),
    pl('BRA', "Gabriel Magalhães", 'DEF', 8),
    pl('BRA', "Ibañez", 'DEF', 9),
    pl('BRA', "Léo Pereira", 'DEF', 10),
    pl('BRA', "Marquinhos", 'DEF', 11),
    pl('BRA', "Bruno Guimarães", 'MED', 12),
    pl('BRA', "Casemiro", 'MED', 13),
    pl('BRA', "Danilo Santos", 'MED', 14),
    pl('BRA', "Éderson", 'MED', 15),
    pl('BRA', "Fabinho", 'MED', 16),
    pl('BRA', "Lucas Paquetá", 'MED', 17),
    pl('BRA', "Endrick", 'MED', 18),
    pl('BRA', "Gabriel Martinelli", 'MED', 19),
    pl('BRA', "Igor Thiago", 'AVA', 20),
    pl('BRA', "Luiz Henrique", 'AVA', 21),
    pl('BRA', "Matheus Cunha", 'AVA', 22),
    pl('BRA', "Neymar", 'AVA', 23),
    pl('BRA', "Raphinha", 'AVA', 24),
    pl('BRA', "Rayan", 'AVA', 25),
    pl('BRA', "Vini Jr", 'AVA', 26),
  ],
  CPV: [
    pl('CPV', "Josimar Dias", 'GR', 1),
    pl('CPV', "Márcio da Rosa", 'GR', 2),
    pl('CPV', "Carlos Santos", 'GR', 3),
    pl('CPV', "Steven Moreira", 'DEF', 4),
    pl('CPV', "Wagner Pina", 'DEF', 5),
    pl('CPV', "Sidny Cabral", 'DEF', 6),
    pl('CPV', "Logan Costa", 'DEF', 7),
    pl('CPV', "Roberto Lopes", 'DEF', 8),
    pl('CPV', "Kelvin Pires", 'DEF', 9),
    pl('CPV', "Ianique Tavares", 'DEF', 10),
    pl('CPV', "Edilson Borges", 'DEF', 11),
    pl('CPV', "Jamiro Monteiro", 'MED', 12),
    pl('CPV', "Deroy Duarte", 'MED', 13),
    pl('CPV', "Kevin Pina", 'MED', 14),
    pl('CPV', "Laros Duarte", 'MED', 15),
    pl('CPV', "Telmo Arcanjo", 'MED', 16),
    pl('CPV', "Yannick Semedo", 'MED', 17),
    pl('CPV', "João Paulo Fernandes", 'MED', 18),
    pl('CPV', "Garry Rodrigues", 'MED', 19),
    pl('CPV', "Jovane Cabral", 'AVA', 20),
    pl('CPV', "Ryan Mendes", 'AVA', 21),
    pl('CPV', "Nuno da Costa", 'AVA', 22),
    pl('CPV', "Dailon Livramento", 'AVA', 23),
    pl('CPV', "Gilson Benchimol", 'AVA', 24),
    pl('CPV', "Willy Semedo", 'AVA', 25),
    pl('CPV', "Hélio Varela", 'AVA', 26),
  ],
  CAN: [
    pl('CAN', "Dayne St. Clair", 'GR', 1),
    pl('CAN', "Maxim Crépeau", 'GR', 2),
    pl('CAN', "Owen Goodman", 'GR', 3),
    pl('CAN', "Alistair Johnston", 'DEF', 4),
    pl('CAN', "Derek Cornelius", 'DEF', 5),
    pl('CAN', "Richie Laryea", 'DEF', 6),
    pl('CAN', "Kiko Sigur", 'DEF', 7),
    pl('CAN', "Joel Waterman", 'DEF', 8),
    pl('CAN', "Luc de Fougerolles", 'DEF', 9),
    pl('CAN', "Moise Bombito", 'DEF', 10),
    pl('CAN', "Alfie Jones", 'DEF', 11),
    pl('CAN', "Alphonso Davies", 'MED', 12),
    pl('CAN', "Stephen Eustáquio", 'MED', 13),
    pl('CAN', "Ismael Koné", 'MED', 14),
    pl('CAN', "Tajon Buchanan", 'MED', 15),
    pl('CAN', "Mathieu Choinière", 'MED', 16),
    pl('CAN', "Ali Ahmed", 'MED', 17),
    pl('CAN', "Nathan Saliba", 'MED', 18),
    pl('CAN', "Liam Millar", 'MED', 19),
    pl('CAN', "Jayden Nelson", 'AVA', 20),
    pl('CAN', "Jacob Shaffelburg", 'AVA', 21),
    pl('CAN', "Jonathan Osorio", 'AVA', 22),
    pl('CAN', "Jonathan David", 'AVA', 23),
    pl('CAN', "Cyle Larin", 'AVA', 24),
    pl('CAN', "Tani Oluwaseyi", 'AVA', 25),
    pl('CAN', "Promise David", 'AVA', 26),
  ],
  QAT: [
    pl('QAT', "Mahmoud Abunada", 'GR', 1),
    pl('QAT', "Meshaal Barsham", 'GR', 2),
    pl('QAT', "Salah Zakaria", 'GR', 3),
    pl('QAT', "Ayoub Al-Alawi", 'DEF', 4),
    pl('QAT', "Boualem Khoukhi", 'DEF', 5),
    pl('QAT', "Homam Al-Amin", 'DEF', 6),
    pl('QAT', "Lucas Mendes", 'DEF', 7),
    pl('QAT', "Issa Laye", 'DEF', 8),
    pl('QAT', "Pedro Miguel", 'DEF', 9),
    pl('QAT', "Al-Hashmi Al-Hussain", 'DEF', 10),
    pl('QAT', "Sultan Al-Brake", 'DEF', 11),
    pl('QAT', "Assim Madibo", 'MED', 12),
    pl('QAT', "Abdulaziz Hatem", 'MED', 13),
    pl('QAT', "Ahmed Fathy", 'MED', 14),
    pl('QAT', "Karim Boudiaf", 'MED', 15),
    pl('QAT', "Jassem Gaber", 'MED', 16),
    pl('QAT', "Mohamed Mannaj", 'MED', 17),
    pl('QAT', "Ahmed Al-Ganehi", 'MED', 18),
    pl('QAT', "Ahmed Alaa", 'MED', 19),
    pl('QAT', "Akram Afif", 'AVA', 20),
    pl('QAT', "AlMoez Ali", 'AVA', 21),
    pl('QAT', "Edmilson Junior", 'AVA', 22),
    pl('QAT', "Hasan Al-Haydos", 'AVA', 23),
    pl('QAT', "Mohammed Muntari", 'AVA', 24),
    pl('QAT', "Tahsin Mohammed", 'AVA', 25),
    pl('QAT', "Youssef Abdulrazzaq", 'AVA', 26),
  ],
  COL: [
    pl('COL', "Camilo Vargas", 'GR', 1),
    pl('COL', "Alvaro Montero", 'GR', 2),
    pl('COL', "David Ospina", 'GR', 3),
    pl('COL', "Davinson Sánchez", 'DEF', 4),
    pl('COL', "Jhon Lucumí", 'DEF', 5),
    pl('COL', "Yerry Mina", 'DEF', 6),
    pl('COL', "Daniel Muñoz", 'DEF', 7),
    pl('COL', "Willer Ditta", 'DEF', 8),
    pl('COL', "Santiago Arias", 'DEF', 9),
    pl('COL', "Johan Mojica", 'DEF', 10),
    pl('COL', "Deiver Machado", 'DEF', 11),
    pl('COL', "Richard Ríos", 'MED', 12),
    pl('COL', "Jefferson Lerma", 'MED', 13),
    pl('COL', "Kevin Castaño", 'MED', 14),
    pl('COL', "Gustavo Puerta", 'MED', 15),
    pl('COL', "Jhon Arias", 'MED', 16),
    pl('COL', "Jorge Carrascal", 'MED', 17),
    pl('COL', "Juan Portilla", 'MED', 18),
    pl('COL', "Juan Quintero", 'MED', 19),
    pl('COL', "James Rodríguez", 'AVA', 20),
    pl('COL', "Jaminton Campaz", 'AVA', 21),
    pl('COL', "Cucho Hernández", 'AVA', 22),
    pl('COL', "Luis Díaz", 'AVA', 23),
    pl('COL', "Luis Suárez", 'AVA', 24),
    pl('COL', "Andrés Gómez", 'AVA', 25),
    pl('COL', "Jhon Córdoba", 'AVA', 26),
  ],
  KOR: [
    pl('KOR', "Kim Seunggyu", 'GR', 1),
    pl('KOR', "Song Bumkeun", 'GR', 2),
    pl('KOR', "Jo Hyeonwoo", 'GR', 3),
    pl('KOR', "Kim Moonhwan", 'DEF', 4),
    pl('KOR', "Kim Min-jae", 'DEF', 5),
    pl('KOR', "Kim Taehyeon", 'DEF', 6),
    pl('KOR', "Park Jinseob", 'DEF', 7),
    pl('KOR', "Seol Youngwoo", 'DEF', 8),
    pl('KOR', "Jens Castrop", 'DEF', 9),
    pl('KOR', "Lee Kihyuk", 'DEF', 10),
    pl('KOR', "Lee Taeseok", 'DEF', 11),
    pl('KOR', "Lee Hanbeom", 'MED', 12),
    pl('KOR', "Jo Wi-Je", 'MED', 13),
    pl('KOR', "Kim Jingyu", 'MED', 14),
    pl('KOR', "Bae Junho", 'MED', 15),
    pl('KOR', "Paik Seungho", 'MED', 16),
    pl('KOR', "Yang Hyunjun", 'MED', 17),
    pl('KOR', "Eom Jisung", 'MED', 18),
    pl('KOR', "Lee Kang-in", 'MED', 19),
    pl('KOR', "Lee Donggyeong", 'AVA', 20),
    pl('KOR', "Lee Jaesung", 'AVA', 21),
    pl('KOR', "Hwang Inbeom", 'AVA', 22),
    pl('KOR', "Hwang Heechan", 'AVA', 23),
    pl('KOR', "Son Heung-min", 'AVA', 24),
    pl('KOR', "Oh Hyeongyu", 'AVA', 25),
    pl('KOR', "Cho Gue-sung", 'AVA', 26),
  ],
  CIV: [
    pl('CIV', "Yahia Fofana", 'GR', 1),
    pl('CIV', "Mohamed Koné", 'GR', 2),
    pl('CIV', "Alban Lafont", 'GR', 3),
    pl('CIV', "Emmanuel Agbadou", 'DEF', 4),
    pl('CIV', "Christopher Operi", 'DEF', 5),
    pl('CIV', "Ousmane Diomande", 'DEF', 6),
    pl('CIV', "Guela Doue", 'DEF', 7),
    pl('CIV', "Ghislan Konan", 'DEF', 8),
    pl('CIV', "Odilon Kossounou", 'DEF', 9),
    pl('CIV', "Evan Ndicka", 'DEF', 10),
    pl('CIV', "Wilfried Singo", 'DEF', 11),
    pl('CIV', "Seko Fofana", 'MED', 12),
    pl('CIV', "Parfait Guiagon", 'MED', 13),
    pl('CIV', "Christ Inao Oulai", 'MED', 14),
    pl('CIV', "Franck Kessie", 'MED', 15),
    pl('CIV', "Ibrahim Sangare", 'MED', 16),
    pl('CIV', "Jean-Mickael Seri", 'MED', 17),
    pl('CIV', "Simon Adingra", 'MED', 18),
    pl('CIV', "Ange-Yoan Bonny", 'MED', 19),
    pl('CIV', "Amad Diallo", 'AVA', 20),
    pl('CIV', "Oumar Diakite", 'AVA', 21),
    pl('CIV', "Yan Diomande", 'AVA', 22),
    pl('CIV', "Evann Guessand", 'AVA', 23),
    pl('CIV', "Nicolas Pepe", 'AVA', 24),
    pl('CIV', "Bazoumana Toure", 'AVA', 25),
    pl('CIV', "Elye Wahi", 'AVA', 26),
  ],
  CRO: [
    pl('CRO', "Dominik Livakovic", 'GR', 1),
    pl('CRO', "Dominik Kotarski", 'GR', 2),
    pl('CRO', "Ivor Pandur", 'GR', 3),
    pl('CRO', "Josko Gvardiol", 'DEF', 4),
    pl('CRO', "Duje Caleta-Car", 'DEF', 5),
    pl('CRO', "Josip Sutalo", 'DEF', 6),
    pl('CRO', "Josip Stanisic", 'DEF', 7),
    pl('CRO', "Marin Pongracic", 'DEF', 8),
    pl('CRO', "Martin Erlic", 'DEF', 9),
    pl('CRO', "Luka Vuskovic", 'DEF', 10),
    pl('CRO', "Luka Modric", 'DEF', 11),
    pl('CRO', "Mateo Kovacic", 'MED', 12),
    pl('CRO', "Mario Pasalic", 'MED', 13),
    pl('CRO', "Nikola Vlasic", 'MED', 14),
    pl('CRO', "Luka Sucic", 'MED', 15),
    pl('CRO', "Martin Baturina", 'MED', 16),
    pl('CRO', "Kristijan Jakic", 'MED', 17),
    pl('CRO', "Petar Sucic", 'MED', 18),
    pl('CRO', "Nikola Moro", 'MED', 19),
    pl('CRO', "Toni Fruk", 'AVA', 20),
    pl('CRO', "Ivan Perisic", 'AVA', 21),
    pl('CRO', "Andrej Kramaric", 'AVA', 22),
    pl('CRO', "Ante Budimir", 'AVA', 23),
    pl('CRO', "Marco Pasalic", 'AVA', 24),
    pl('CRO', "Petar Musa", 'AVA', 25),
    pl('CRO', "Igor Matanovic", 'AVA', 26),
  ],
  CUW: [
    pl('CUW', "Tyrick Bodak", 'GR', 1),
    pl('CUW', "Trevor Doornbusch", 'GR', 2),
    pl('CUW', "Eloy Room", 'GR', 3),
    pl('CUW', "Riechedly Bazoer", 'DEF', 4),
    pl('CUW', "Joshua Brenet", 'DEF', 5),
    pl('CUW', "Roshon Van Eijma", 'DEF', 6),
    pl('CUW', "Sherel Floranus", 'DEF', 7),
    pl('CUW', "Deveron Fonville", 'DEF', 8),
    pl('CUW', "Jurien Gaari", 'DEF', 9),
    pl('CUW', "Armando Obispo", 'DEF', 10),
    pl('CUW', "Shurandy Sambo", 'DEF', 11),
    pl('CUW', "Juninho Bacuna", 'MED', 12),
    pl('CUW', "Leandro Bacuna", 'MED', 13),
    pl('CUW', "Livano Comenencia", 'MED', 14),
    pl('CUW', "Kevin Felida", 'MED', 15),
    pl('CUW', "AR'Jany Martha", 'MED', 16),
    pl('CUW', "Tyrese Noslin", 'MED', 17),
    pl('CUW', "Godfried Roemeratoe", 'MED', 18),
    pl('CUW', "Jeremy Antonisse", 'MED', 19),
    pl('CUW', "Tahith Chong", 'AVA', 20),
    pl('CUW', "Kenji Gorré", 'AVA', 21),
    pl('CUW', "Sontje Hansen", 'AVA', 22),
    pl('CUW', "Gervane Kastaneer", 'AVA', 23),
    pl('CUW', "Brandley Kuwas", 'AVA', 24),
    pl('CUW', "Jurgen Locadia", 'AVA', 25),
    pl('CUW', "Jearl Margaritha", 'AVA', 26),
  ],
  EGY: [
    pl('EGY', "Mohamed El Shenawy", 'GR', 1),
    pl('EGY', "Mostafa Shobeir", 'GR', 2),
    pl('EGY', "El Mahdy Soliman", 'GR', 3),
    pl('EGY', "Mohamed Alaa", 'DEF', 4),
    pl('EGY', "Mohamed Hany", 'DEF', 5),
    pl('EGY', "Tarek Alaa", 'DEF', 6),
    pl('EGY', "Hamdi Fathi", 'DEF', 7),
    pl('EGY', "Ramy Rabia", 'DEF', 8),
    pl('EGY', "Yasser Ibrahim", 'DEF', 9),
    pl('EGY', "Hossam Abdelmaguid", 'DEF', 10),
    pl('EGY', "Mohamed Abdelmonem", 'DEF', 11),
    pl('EGY', "Ahmed Fatouh", 'MED', 12),
    pl('EGY', "Karim Hafez", 'MED', 13),
    pl('EGY', "Marwan Attia", 'MED', 14),
    pl('EGY', "Mohannad Lasheen", 'MED', 15),
    pl('EGY', "Nabil Emad Dunga", 'MED', 16),
    pl('EGY', "Mahmoud Saber", 'MED', 17),
    pl('EGY', "Ahmed Sayed Zizo", 'MED', 18),
    pl('EGY', "Mahmoud Trezeguet", 'MED', 19),
    pl('EGY', "Emam Ashour", 'AVA', 20),
    pl('EGY', "Mostafa Ziko", 'AVA', 21),
    pl('EGY', "Ibrahim Adel", 'AVA', 22),
    pl('EGY', "Haitham Hassan", 'AVA', 23),
    pl('EGY', "Mohamed Salah", 'AVA', 24),
    pl('EGY', "Omar Marmoush", 'AVA', 25),
    pl('EGY', "Hamza Abdel Karim", 'AVA', 26),
  ],
  ECU: [
    pl('ECU', "Hernán Galíndez", 'GR', 1),
    pl('ECU', "Moisés Ramírez", 'GR', 2),
    pl('ECU', "Gonzalo Valle", 'GR', 3),
    pl('ECU', "Willian Pacho", 'DEF', 4),
    pl('ECU', "Piero Hincapié", 'DEF', 5),
    pl('ECU', "Joel Ordóñez", 'DEF', 6),
    pl('ECU', "Jackson Porozo", 'DEF', 7),
    pl('ECU', "Félix Torres", 'DEF', 8),
    pl('ECU', "Pervis Estupiñán", 'DEF', 9),
    pl('ECU', "Yaimar Medina", 'DEF', 10),
    pl('ECU', "Ángelo Preciado", 'DEF', 11),
    pl('ECU', "Moisés Caicedo", 'MED', 12),
    pl('ECU', "Jordy Alcívar", 'MED', 13),
    pl('ECU', "Pedro Vite", 'MED', 14),
    pl('ECU', "Denil Castillo", 'MED', 15),
    pl('ECU', "Alan Franco", 'MED', 16),
    pl('ECU', "Kendry Páez", 'MED', 17),
    pl('ECU', "Nilson Angulo", 'MED', 18),
    pl('ECU', "Gonzalo Plata", 'MED', 19),
    pl('ECU', "John Yeboah", 'AVA', 20),
    pl('ECU', "Enner Valencia", 'AVA', 21),
    pl('ECU', "Jordy Caicedo", 'AVA', 22),
    pl('ECU', "Jeremy Arévalo", 'AVA', 23),
    pl('ECU', "Alan Minda", 'AVA', 24),
    pl('ECU', "Anthony Valencia", 'AVA', 25),
    pl('ECU', "Kevin Rodríguez", 'AVA', 26),
  ],
  ESP: [
    pl('ESP', "Unai Simón", 'GR', 1),
    pl('ESP', "David Raya", 'GR', 2),
    pl('ESP', "Joan García", 'GR', 3),
    pl('ESP', "Cucurella", 'DEF', 4),
    pl('ESP', "Grimaldo", 'DEF', 5),
    pl('ESP', "Cubarsí", 'DEF', 6),
    pl('ESP', "Laporte", 'DEF', 7),
    pl('ESP', "Pubill", 'DEF', 8),
    pl('ESP', "Eric García", 'DEF', 9),
    pl('ESP', "Marcos Llorente", 'DEF', 10),
    pl('ESP', "Pedro Porro", 'DEF', 11),
    pl('ESP', "Pedri", 'MED', 12),
    pl('ESP', "Fabián Ruíz", 'MED', 13),
    pl('ESP', "Zubimendi", 'MED', 14),
    pl('ESP', "Gavi", 'MED', 15),
    pl('ESP', "Rodri", 'MED', 16),
    pl('ESP', "Alex Baena", 'MED', 17),
    pl('ESP', "Merino", 'MED', 18),
    pl('ESP', "Oyarzabal", 'MED', 19),
    pl('ESP', "Dani Olmo", 'AVA', 20),
    pl('ESP', "Nico Williams", 'AVA', 21),
    pl('ESP', "Yeremy Pino", 'AVA', 22),
    pl('ESP', "Ferran Torres", 'AVA', 23),
    pl('ESP', "Borja Iglesias", 'AVA', 24),
    pl('ESP', "Víctor Muñoz", 'AVA', 25),
    pl('ESP', "Lamine Yamal", 'AVA', 26),
  ],
  SCO: [
    pl('SCO', "Craig Gordon", 'GR', 1),
    pl('SCO', "Angus Gunn", 'GR', 2),
    pl('SCO', "Liam Kelly", 'GR', 3),
    pl('SCO', "Grant Hanley", 'DEF', 4),
    pl('SCO', "Jack Hendry", 'DEF', 5),
    pl('SCO', "Aaron Hickey", 'DEF', 6),
    pl('SCO', "Dom Hyam", 'DEF', 7),
    pl('SCO', "Soctt McKenna", 'DEF', 8),
    pl('SCO', "Nathan Patterson", 'DEF', 9),
    pl('SCO', "Anthony Ralston", 'DEF', 10),
    pl('SCO', "Andy Robertson", 'DEF', 11),
    pl('SCO', "John Souttar", 'MED', 12),
    pl('SCO', "Kieran Tierney", 'MED', 13),
    pl('SCO', "Ryan Christie", 'MED', 14),
    pl('SCO', "Findlay Curtis", 'MED', 15),
    pl('SCO', "Lewis Fergunson", 'MED', 16),
    pl('SCO', "Ben Gannon-Doak", 'MED', 17),
    pl('SCO', "Tyler Fletcher", 'MED', 18),
    pl('SCO', "John McGinn", 'MED', 19),
    pl('SCO', "Kenny McLean", 'AVA', 20),
    pl('SCO', "Scott McTominay", 'AVA', 21),
    pl('SCO', "Che Adams", 'AVA', 22),
    pl('SCO', "Lyndon Dykes", 'AVA', 23),
    pl('SCO', "George Hirst", 'AVA', 24),
    pl('SCO', "Lawrence Shankland", 'AVA', 25),
    pl('SCO', "Ross Steward", 'AVA', 26),
  ],
  USA: [
    pl('USA', "Chris Brady", 'GR', 1),
    pl('USA', "Matt Freese", 'GR', 2),
    pl('USA', "Matt Turner", 'GR', 3),
    pl('USA', "Alex Freeman", 'DEF', 4),
    pl('USA', "Antonee Robinson", 'DEF', 5),
    pl('USA', "Auston Trusty", 'DEF', 6),
    pl('USA', "Chris Richards", 'DEF', 7),
    pl('USA', "Mark McKenzie", 'DEF', 8),
    pl('USA', "Max Arfsten", 'DEF', 9),
    pl('USA', "Sergiño Dest", 'DEF', 10),
    pl('USA', "Tim Ream", 'DEF', 11),
    pl('USA', "Miles Robinson", 'MED', 12),
    pl('USA', "Joe Scally", 'MED', 13),
    pl('USA', "Brenden Aaronson", 'MED', 15),
    pl('USA', "Cristian Roldan", 'MED', 16),
    pl('USA', "Gio Reyna", 'MED', 17),
    pl('USA', "Malik Tillman", 'MED', 18),
    pl('USA', "Tyler Adams", 'MED', 19),
    pl('USA', "Weston McKennie", 'MED', 20),
    pl('USA', "Alex Zendejas", 'AVA', 21),
    pl('USA', "Christian Pulisic", 'AVA', 22),
    pl('USA', "Folarin Balogun", 'AVA', 23),
    pl('USA', "Haji Wright", 'AVA', 24),
    pl('USA', "Ricardo Pepi", 'AVA', 25),
    pl('USA', "Tim Weah", 'AVA', 26),
  ],
  FRA: [
    pl('FRA', "Mike Maignan", 'GR', 1),
    pl('FRA', "Robin Risser", 'GR', 2),
    pl('FRA', "Brice Samba", 'GR', 3),
    pl('FRA', "Lucas Digne", 'DEF', 4),
    pl('FRA', "Malo Gusto", 'DEF', 5),
    pl('FRA', "Lucas Hernández", 'DEF', 6),
    pl('FRA', "Theo Hernandez", 'DEF', 7),
    pl('FRA', "Ibrahima Konaté", 'DEF', 8),
    pl('FRA', "Jules Koundé", 'DEF', 9),
    pl('FRA', "Maxence Lacroix", 'DEF', 10),
    pl('FRA', "William Saliba", 'DEF', 11),
    pl('FRA', "Dayot Upamecano", 'MED', 12),
    pl('FRA', "N'Golo Kanté", 'MED', 13),
    pl('FRA', "Manu Koné", 'MED', 14),
    pl('FRA', "Adrien Rabiot", 'MED', 15),
    pl('FRA', "Aurélien Tchouaméni", 'MED', 16),
    pl('FRA', "Warren Zaïre-Emery", 'MED', 17),
    pl('FRA', "Maghnes Akliouche", 'MED', 18),
    pl('FRA', "Bradley Barcola", 'MED', 19),
    pl('FRA', "Rayan Cherki", 'AVA', 20),
    pl('FRA', "Ousmane Dembélé", 'AVA', 21),
    pl('FRA', "Désiré Doué", 'AVA', 22),
    pl('FRA', "Jean-Philippe Mateta", 'AVA', 23),
    pl('FRA', "Kylian Mbappé", 'AVA', 24),
    pl('FRA', "Michael Olise", 'AVA', 25),
    pl('FRA', "Marcus Thuram", 'AVA', 26),
  ],
  GHA: [
    pl('GHA', "Benjamin Asare", 'GR', 1),
    pl('GHA', "Lawrence Ati-Zigi", 'GR', 2),
    pl('GHA', "Joseph Anang", 'GR', 3),
    pl('GHA', "Baba Abdul Rahman", 'DEF', 4),
    pl('GHA', "Gideoh Mensah", 'DEF', 5),
    pl('GHA', "Marvin Senaya", 'DEF', 6),
    pl('GHA', "Alidu Seidu", 'DEF', 7),
    pl('GHA', "Abdul Mumin", 'DEF', 8),
    pl('GHA', "Jerome Opoku", 'DEF', 9),
    pl('GHA', "Jonas Adjetey", 'DEF', 10),
    pl('GHA', "Kojo Oppong Peprah", 'DEF', 11),
    pl('GHA', "Derrick Luckassen", 'MED', 12),
    pl('GHA', "Elisha Owusu", 'MED', 13),
    pl('GHA', "Thomas Partey", 'MED', 14),
    pl('GHA', "Kwasi Sibo", 'MED', 15),
    pl('GHA', "Augustine Boakye", 'MED', 16),
    pl('GHA', "Caleb Yirenkyi", 'MED', 17),
    pl('GHA', "Abdul Fatawu Issahaku", 'MED', 18),
    pl('GHA', "Christopher Bonsu Baah", 'MED', 19),
    pl('GHA', "Ernest Nuamah", 'AVA', 20),
    pl('GHA', "Antoine Semenyo", 'AVA', 21),
    pl('GHA', "Brandon Thomas-Asante", 'AVA', 22),
    pl('GHA', "Kamal Deen Sulemana", 'AVA', 23),
    pl('GHA', "Prince Kwabena Adu", 'AVA', 24),
    pl('GHA', "Iñaki Williams", 'AVA', 25),
    pl('GHA', "Jordan Ayew", 'AVA', 26),
  ],
  HAI: [
    pl('HAI', "Johnny Placide", 'GR', 1),
    pl('HAI', "Alexandre Pierre", 'GR', 2),
    pl('HAI', "Josué Duverger", 'GR', 3),
    pl('HAI', "Carlens Arcus", 'DEF', 4),
    pl('HAI', "Garven-Michée Metusala", 'DEF', 5),
    pl('HAI', "Wilguens Pauguain", 'DEF', 6),
    pl('HAI', "Duke Lacroix", 'DEF', 7),
    pl('HAI', "Martin Experience", 'DEF', 8),
    pl('HAI', "JK Duverne", 'DEF', 9),
    pl('HAI', "Ricardo Ade", 'DEF', 10),
    pl('HAI', "Hannes Delcroix", 'DEF', 11),
    pl('HAI', "Keeto Thermoncy", 'MED', 12),
    pl('HAI', "Carl-Fred Sainthe", 'MED', 13),
    pl('HAI', "Jean-Jacques Danley", 'MED', 14),
    pl('HAI', "Jeanricner Bellegarde", 'MED', 15),
    pl('HAI', "Pierre Woodenski", 'MED', 16),
    pl('HAI', "Dominique Simon", 'MED', 17),
    pl('HAI', "Louicius Deedson", 'MED', 18),
    pl('HAI', "Ruben Providence", 'MED', 19),
    pl('HAI', "Josué Casimir", 'AVA', 20),
    pl('HAI', "Derrick Etienne", 'AVA', 21),
    pl('HAI', "Wilson Isidor", 'AVA', 22),
    pl('HAI', "Duckens Nazon", 'AVA', 23),
    pl('HAI', "Frantzdy Pierrot", 'AVA', 24),
    pl('HAI', "Yassin Fortune", 'AVA', 25),
    pl('HAI', "Lenny Joseph", 'AVA', 26),
  ],
  NED: [
    pl('NED', "Mark Flekken", 'GR', 1),
    pl('NED', "Robin Roefs", 'GR', 2),
    pl('NED', "Bart Verbruggen", 'GR', 3),
    pl('NED', "Nathan Aké", 'DEF', 4),
    pl('NED', "Virgil van Dijk", 'DEF', 5),
    pl('NED', "Denzel Dumfries", 'DEF', 6),
    pl('NED', "Jorrel Hato", 'DEF', 7),
    pl('NED', "Jan Paul van Hecke", 'DEF', 8),
    pl('NED', "Lutsharel Geertruida", 'DEF', 9),
    pl('NED', "Micky van de Ven", 'DEF', 10),
    pl('NED', "Ryan Gravenberch", 'DEF', 11),
    pl('NED', "Frenkie de Jong", 'MED', 12),
    pl('NED', "Teun Koopmeiners", 'MED', 13),
    pl('NED', "Tijjani Reijnders", 'MED', 14),
    pl('NED', "Marten de Roon", 'MED', 15),
    pl('NED', "Guus Til", 'MED', 16),
    pl('NED', "Quinten Timber", 'MED', 17),
    pl('NED', "Mats Wieffer", 'MED', 18),
    pl('NED', "Memphis Depay", 'MED', 19),
    pl('NED', "Brian Brobbey", 'AVA', 20),
    pl('NED', "Cody Gakpo", 'AVA', 21),
    pl('NED', "Justin Kluivert", 'AVA', 22),
    pl('NED', "Noa Lang", 'AVA', 23),
    pl('NED', "Donyell Malen", 'AVA', 24),
    pl('NED', "Crysencio Summerville", 'AVA', 25),
    pl('NED', "Wout Weghorst", 'AVA', 26),
  ],
  ENG: [
    pl('ENG', "Jordan Pickford", 'GR', 1),
    pl('ENG', "Dean Henderson", 'GR', 2),
    pl('ENG', "James Trafford", 'GR', 3),
    pl('ENG', "Reece James", 'DEF', 4),
    pl('ENG', "Ezri Konsa", 'DEF', 5),
    pl('ENG', "Jarell Quansah", 'DEF', 6),
    pl('ENG', "John Stones", 'DEF', 7),
    pl('ENG', "Marc Guehi", 'DEF', 8),
    pl('ENG', "Dan Burn", 'DEF', 9),
    pl('ENG', "Nico O'Reilly", 'DEF', 10),
    pl('ENG', "Djed Spence", 'DEF', 11),
    pl('ENG', "Chalobah", 'MED', 12),
    pl('ENG', "Declan Rice", 'MED', 13),
    pl('ENG', "Elliot Anderson", 'MED', 14),
    pl('ENG', "Kobbie Mainoo", 'MED', 15),
    pl('ENG', "Jordan Henderson", 'MED', 16),
    pl('ENG', "Morgan Rogers", 'MED', 17),
    pl('ENG', "Jude Bellingham", 'MED', 18),
    pl('ENG', "Eberechi Eze", 'MED', 19),
    pl('ENG', "Harry Kane", 'AVA', 20),
    pl('ENG', "Ivan Toney", 'AVA', 21),
    pl('ENG', "Ollie Watkins", 'AVA', 22),
    pl('ENG', "Bukayo Saka", 'AVA', 23),
    pl('ENG', "Marcus Rashford", 'AVA', 24),
    pl('ENG', "Anthony Gordon", 'AVA', 25),
    pl('ENG', "Noni Madueke", 'AVA', 26),
  ],
  IRN: [
    pl('IRN', "Alireza Beiranvand", 'GR', 1),
    pl('IRN', "Seyed Hossein Hosseini", 'GR', 2),
    pl('IRN', "Payam Niazmand", 'GR', 3),
    pl('IRN', "Danial Eiri", 'DEF', 4),
    pl('IRN', "Ehsan Hajsafi", 'DEF', 5),
    pl('IRN', "Saleh Hardani", 'DEF', 6),
    pl('IRN', "Hossein Kanaani", 'DEF', 7),
    pl('IRN', "Shoja Khalilzadeh", 'DEF', 8),
    pl('IRN', "Milad Mohammadi", 'DEF', 9),
    pl('IRN', "Ali Nemati", 'DEF', 10),
    pl('IRN', "Ramin Rezaeian", 'DEF', 11),
    pl('IRN', "Rouzbeh Cheshmi", 'MED', 12),
    pl('IRN', "Saeid Ezatolahi", 'MED', 13),
    pl('IRN', "Mehdi Ghaedi", 'MED', 14),
    pl('IRN', "Saman Ghoddos", 'MED', 15),
    pl('IRN', "Mohammad Ghorbani", 'MED', 16),
    pl('IRN', "Alireza Jahanbakhsh", 'MED', 17),
    pl('IRN', "Mohammad Mohebi", 'MED', 18),
    pl('IRN', "Amir Mohammad Razzaghinia", 'MED', 19),
    pl('IRN', "Mehdi Torabi", 'AVA', 20),
    pl('IRN', "Aria Yousefi", 'AVA', 21),
    pl('IRN', "Ali Alipour", 'AVA', 22),
    pl('IRN', "Dennis Dargahi", 'AVA', 23),
    pl('IRN', "Amirhossein Hosseinzadeh", 'AVA', 24),
    pl('IRN', "Mehdi Taremi", 'AVA', 25),
    pl('IRN', "Shahriar Moghanlou", 'AVA', 26),
  ],
  IRQ: [
    pl('IRQ', "Jalal Hassan", 'GR', 1),
    pl('IRQ', "Ahmed Basil", 'GR', 2),
    pl('IRQ', "Fahad Talib", 'GR', 3),
    pl('IRQ', "Mirkhas Doski", 'DEF', 4),
    pl('IRQ', "Ahmed Maknzi", 'DEF', 5),
    pl('IRQ', "Manaf Younis", 'DEF', 6),
    pl('IRQ', "Akam Hashim", 'DEF', 7),
    pl('IRQ', "Zaid Tahsin", 'DEF', 8),
    pl('IRQ', "Rebin Sulaka", 'DEF', 9),
    pl('IRQ', "Frans Putros", 'DEF', 10),
    pl('IRQ', "Hussein Ali", 'DEF', 11),
    pl('IRQ', "Mustafa Saadoun", 'MED', 12),
    pl('IRQ', "Aimar Sher", 'MED', 13),
    pl('IRQ', "Zaid Ismail", 'MED', 14),
    pl('IRQ', "Amir Al-Ammari", 'MED', 15),
    pl('IRQ', "Kevin Yaqoub", 'MED', 16),
    pl('IRQ', "Zidane Iqbal", 'MED', 17),
    pl('IRQ', "Ahmed Qasim", 'MED', 18),
    pl('IRQ', "Ibrahim Bayesh", 'MED', 19),
    pl('IRQ', "Ali Jassim", 'AVA', 20),
    pl('IRQ', "Yousef Amin", 'AVA', 21),
    pl('IRQ', "Marco Faraj", 'AVA', 22),
    pl('IRQ', "Ali Al-Hamadi", 'AVA', 23),
    pl('IRQ', "Aymen Hussein", 'AVA', 24),
    pl('IRQ', "Mohanad Ali", 'AVA', 25),
    pl('IRQ', "Ali Youssef", 'AVA', 26),
  ],
  JPN: [
    pl('JPN', "Zion Suzuki", 'GR', 1),
    pl('JPN', "Keisuke Osako", 'GR', 2),
    pl('JPN', "Tomoki Hayakawa", 'GR', 3),
    pl('JPN', "Hiroki Ito", 'DEF', 4),
    pl('JPN', "Junnosuke Suzuki", 'DEF', 5),
    pl('JPN', "Ayumu Seko", 'DEF', 6),
    pl('JPN', "Shogo Taniguchi", 'DEF', 7),
    pl('JPN', "Tsuyoshi Watanabe", 'DEF', 8),
    pl('JPN', "Ko Itakura", 'DEF', 9),
    pl('JPN', "Takehiro Tomiyasu", 'DEF', 10),
    pl('JPN', "Yukinari Sugawara", 'DEF', 11),
    pl('JPN', "Yuto Nagatomo", 'MED', 12),
    pl('JPN', "Daichi Kamada", 'MED', 13),
    pl('JPN', "Ao Tanaka", 'MED', 14),
    pl('JPN', "Kaishu Sano", 'MED', 15),
    pl('JPN', "Shuto Machino", 'MED', 16),
    pl('JPN', "Keito Nakamura", 'MED', 17),
    pl('JPN', "Daizen Maeda", 'MED', 18),
    pl('JPN', "Ritsu Doan", 'MED', 19),
    pl('JPN', "Yuito Suzuki", 'AVA', 20),
    pl('JPN', "Junya Ito", 'AVA', 21),
    pl('JPN', "Ayase Ueda", 'AVA', 22),
    pl('JPN', "Koki Ogawa", 'AVA', 23),
    pl('JPN', "Kento Shiogai", 'AVA', 24),
    pl('JPN', "Keisuke Goto", 'AVA', 25),
    pl('JPN', "Takefusa Kubo", 'AVA', 26),
  ],
  JOR: [
    pl('JOR', "Yazeed Abu Laila", 'GR', 1),
    pl('JOR', "Abdullah Al-Fakhouri", 'GR', 2),
    pl('JOR', "Nour Bani Attiah", 'GR', 3),
    pl('JOR', "Abdallah Nasib", 'DEF', 4),
    pl('JOR', "Saed Al-Rosan", 'DEF', 5),
    pl('JOR', "Yazan Al-Arab", 'DEF', 6),
    pl('JOR', "Saleem Obaid", 'DEF', 7),
    pl('JOR', "Mohammad Abualnadi", 'DEF', 8),
    pl('JOR', "Husam Abu Dahab", 'DEF', 9),
    pl('JOR', "Ihsan Haddad", 'DEF', 10),
    pl('JOR', "Anas Badawi", 'DEF', 11),
    pl('JOR', "Mohannad Abu Taha", 'MED', 12),
    pl('JOR', "Mohammad Abu Hashish", 'MED', 13),
    pl('JOR', "Mohammad Abu Ghoush", 'MED', 14),
    pl('JOR', "Nour Al-Rawabdeh", 'MED', 15),
    pl('JOR', "Nizar Al-Rashdan", 'MED', 16),
    pl('JOR', "Ibrahim Sadeh", 'MED', 17),
    pl('JOR', "Rajaei Ayed", 'MED', 18),
    pl('JOR', "Odeh Fakhouri", 'MED', 19),
    pl('JOR', "Amer Jamous", 'AVA', 20),
    pl('JOR', "Mohammad Al-Dawoud", 'AVA', 21),
    pl('JOR', "Mahmoud Al-Mardi", 'AVA', 22),
    pl('JOR', "Musa Al-Taamari", 'AVA', 23),
    pl('JOR', "Mohammad Abu Zrayq", 'AVA', 24),
    pl('JOR', "Ali Al-Azaizeh", 'AVA', 25),
    pl('JOR', "Ali Olwan", 'AVA', 26),
  ],
  MAR: [
    pl('MAR', "Bounou", 'GR', 1),
    pl('MAR', "El Kajoui", 'GR', 2),
    pl('MAR', "Tagnaouti", 'GR', 3),
    pl('MAR', "Mazraoui", 'DEF', 4),
    pl('MAR', "Salah-Eddine", 'DEF', 5),
    pl('MAR', "Belammari", 'DEF', 6),
    pl('MAR', "Hakimi", 'DEF', 7),
    pl('MAR', "El Ouahdi", 'DEF', 8),
    pl('MAR', "Marwane Saadane", 'DEF', 9),
    pl('MAR', "Riad", 'DEF', 10),
    pl('MAR', "Halhal", 'DEF', 11),
    pl('MAR', "Diop", 'MED', 12),
    pl('MAR', "El Mourabet", 'MED', 13),
    pl('MAR', "Bouaddi", 'MED', 14),
    pl('MAR', "El Aynaoui", 'MED', 15),
    pl('MAR', "Amrabat", 'MED', 16),
    pl('MAR', "Ounahi", 'MED', 17),
    pl('MAR', "El Khannouss", 'MED', 18),
    pl('MAR', "Saibari", 'MED', 19),
    pl('MAR', "Sbai", 'AVA', 20),
    pl('MAR', "Talbi", 'AVA', 21),
    pl('MAR', "Rahimi", 'AVA', 22),
    pl('MAR', "El Kaabi", 'AVA', 23),
    pl('MAR', "Brahim Díaz", 'AVA', 24),
    pl('MAR', "Gessime", 'AVA', 25),
    pl('MAR', "Echghouyabe", 'AVA', 26),
  ],
  MEX: [
    pl('MEX', "Raúl Rangel", 'GR', 1),
    pl('MEX', "Carlos Acevedo", 'GR', 2),
    pl('MEX', "Guillermo Ochoa", 'GR', 3),
    pl('MEX', "Jorge Sánchez", 'DEF', 4),
    pl('MEX', "César Montes", 'DEF', 5),
    pl('MEX', "Edson Álvarez", 'DEF', 6),
    pl('MEX', "Joah Vásquez", 'DEF', 7),
    pl('MEX', "Erik Lira", 'DEF', 8),
    pl('MEX', "Luis Romo", 'DEF', 9),
    pl('MEX', "Israel Reyes", 'DEF', 10),
    pl('MEX', "Mateo Chávez", 'DEF', 11),
    pl('MEX', "Jesús Gallardo", 'MED', 12),
    pl('MEX', "Álvaro Fidalgo", 'MED', 13),
    pl('MEX', "Orbelín Pineda", 'MED', 14),
    pl('MEX', "Obed Vargas", 'MED', 15),
    pl('MEX', "Gilberto Mora", 'MED', 16),
    pl('MEX', "César Huerta", 'MED', 17),
    pl('MEX', "Luis Chávez", 'MED', 18),
    pl('MEX', "Roberto Alvarado", 'MED', 19),
    pl('MEX', "Brian Gutiérrez", 'AVA', 20),
    pl('MEX', "Raúl Jiménez", 'AVA', 21),
    pl('MEX', "Alexis Veja", 'AVA', 22),
    pl('MEX', "Santiago Giménez", 'AVA', 23),
    pl('MEX', "Armando González", 'AVA', 24),
    pl('MEX', "Julián Quiñones", 'AVA', 25),
    pl('MEX', "Guillermo Martínez", 'AVA', 26),
  ],
  NOR: [
    pl('NOR', "Egil Selvik", 'GR', 1),
    pl('NOR', "Orjan Nyland", 'GR', 2),
    pl('NOR', "Sander Tangvik", 'GR', 3),
    pl('NOR', "Kristoffer Ajer", 'DEF', 4),
    pl('NOR', "Fredrik Bjorkan", 'DEF', 5),
    pl('NOR', "Henrik Falchener", 'DEF', 6),
    pl('NOR', "Sondre Langas", 'DEF', 7),
    pl('NOR', "Torbjorn Heggem", 'DEF', 8),
    pl('NOR', "Holmgren Pedersen", 'DEF', 9),
    pl('NOR', "Julian Ryerson", 'DEF', 10),
    pl('NOR', "Leo Ostigard", 'DEF', 11),
    pl('NOR', "David Moller", 'MED', 12),
    pl('NOR', "Martin Odegaard", 'MED', 13),
    pl('NOR', "Patrick Berg", 'MED', 14),
    pl('NOR', "Kristian Thorstvedt", 'MED', 15),
    pl('NOR', "Thelo Aasgaard", 'MED', 16),
    pl('NOR', "Fredrik Aursnes", 'MED', 17),
    pl('NOR', "Sander Berge", 'MED', 18),
    pl('NOR', "Morten Thorsby", 'MED', 19),
    pl('NOR', "Strand Larsen", 'AVA', 20),
    pl('NOR', "Oscar Bobb", 'AVA', 21),
    pl('NOR', "Erling Haaland", 'AVA', 22),
    pl('NOR', "Andreas Schjelderup", 'AVA', 23),
    pl('NOR', "Jens Petter Hauge", 'AVA', 24),
    pl('NOR', "Antonio Nusa", 'AVA', 25),
    pl('NOR', "Alexander Sorloth", 'AVA', 26),
  ],
  NZL: [
    pl('NZL', "Max Crocombe", 'GR', 1),
    pl('NZL', "Alex Paulsen", 'GR', 2),
    pl('NZL', "Michael Woud", 'GR', 3),
    pl('NZL', "Tyler Bindon", 'DEF', 4),
    pl('NZL', "Michael Boxall", 'DEF', 5),
    pl('NZL', "Liberato Cacace", 'DEF', 6),
    pl('NZL', "Francis de Vries", 'DEF', 7),
    pl('NZL', "Callan Elliot", 'DEF', 8),
    pl('NZL', "Tim Payne", 'DEF', 9),
    pl('NZL', "Nando Pijnaker", 'DEF', 10),
    pl('NZL', "Tommy Smith", 'DEF', 11),
    pl('NZL', "Finn Surman", 'MED', 12),
    pl('NZL', "Lachlan Bayliss", 'MED', 13),
    pl('NZL', "Joe Bell", 'MED', 14),
    pl('NZL', "Logan Rogerson", 'MED', 15),
    pl('NZL', "Ben Old", 'MED', 16),
    pl('NZL', "Alex Rufer", 'MED', 17),
    pl('NZL', "Sarpreet Singh", 'MED', 18),
    pl('NZL', "Marko Stamenic", 'MED', 19),
    pl('NZL', "Ryan Thomas", 'AVA', 20),
    pl('NZL', "Kosta Barbarouses", 'AVA', 21),
    pl('NZL', "Eli Just", 'AVA', 22),
    pl('NZL', "Callum McCowatt", 'AVA', 23),
    pl('NZL', "Jesse Randall", 'AVA', 24),
    pl('NZL', "Ben Waine", 'AVA', 25),
    pl('NZL', "Chris Wood", 'AVA', 26),
  ],
  PAN: [
    pl('PAN', "Orlando Mosquera", 'GR', 1),
    pl('PAN', "Luis Mejía", 'GR', 2),
    pl('PAN', "César Samudio", 'GR', 3),
    pl('PAN', "César Blackman", 'DEF', 4),
    pl('PAN', "Jorge Gutiérrez", 'DEF', 5),
    pl('PAN', "Amir Murillo", 'DEF', 6),
    pl('PAN', "Fidel Escobar", 'DEF', 7),
    pl('PAN', "Andrés Andrade", 'DEF', 8),
    pl('PAN', "Edgardo Fariña", 'DEF', 9),
    pl('PAN', "José Córdoba", 'DEF', 10),
    pl('PAN', "Eric David", 'DEF', 11),
    pl('PAN', "Jiovany Ramos", 'MED', 12),
    pl('PAN', "Roderick Miller", 'MED', 13),
    pl('PAN', "Aníbal Godoy", 'MED', 14),
    pl('PAN', "Adalberto Carrasquilla", 'MED', 15),
    pl('PAN', "Carlos Harvey", 'MED', 16),
    pl('PAN', "Cristian Martínez", 'MED', 17),
    pl('PAN', "José Luis Rodríguez", 'MED', 18),
    pl('PAN', "César Yanis", 'MED', 19),
    pl('PAN', "Yoel Bárcenas", 'AVA', 20),
    pl('PAN', "Alberto Quintero", 'AVA', 21),
    pl('PAN', "Azarías Londoño", 'AVA', 22),
    pl('PAN', "Ismael Díaz", 'AVA', 23),
    pl('PAN', "Cecilio Waterman", 'AVA', 24),
    pl('PAN', "José Fajardo", 'AVA', 25),
    pl('PAN', "Tomás Rodríguez", 'AVA', 26),
  ],
  PAR: [
    pl('PAR', "Orlando Gill", 'GR', 1),
    pl('PAR', "Gatito Fernández", 'GR', 2),
    pl('PAR', "Gastón Olveira", 'GR', 3),
    pl('PAR', "Juan Cáceres", 'DEF', 4),
    pl('PAR', "José Canale", 'DEF', 5),
    pl('PAR', "Fabián Balbuena", 'DEF', 6),
    pl('PAR', "Omar Alderete", 'DEF', 7),
    pl('PAR', "Gustavo Gómez", 'DEF', 8),
    pl('PAR', "Alexandro Maidana", 'DEF', 9),
    pl('PAR', "Junior Alonso", 'DEF', 10),
    pl('PAR', "Gustavo Velázquez", 'DEF', 11),
    pl('PAR', "Braian Ojeda", 'MED', 12),
    pl('PAR', "Damián Bobadilla", 'MED', 13),
    pl('PAR', "Andrés Cubas", 'MED', 14),
    pl('PAR', "Diego Gómez", 'MED', 15),
    pl('PAR', "Alejandro Romero Gamarra", 'MED', 16),
    pl('PAR', "Mauricio", 'MED', 17),
    pl('PAR', "Matías Galarza", 'MED', 18),
    pl('PAR', "Gustavo Caballero", 'MED', 19),
    pl('PAR', "Ramón Sosa", 'AVA', 20),
    pl('PAR', "Miguel Almirón", 'AVA', 21),
    pl('PAR', "Gabriel Ávalos", 'AVA', 22),
    pl('PAR', "Isidro Pitta", 'AVA', 23),
    pl('PAR', "Álex Arce", 'AVA', 24),
    pl('PAR', "Julio Enciso", 'AVA', 25),
    pl('PAR', "Antonio Sanabria", 'AVA', 26),
  ],
  POR: [
    pl('POR', "Diogo Costa", 'GR', 1),
    pl('POR', "José Sá", 'GR', 2),
    pl('POR', "Rui Silva", 'GR', 3),
    pl('POR', "Diogo Dalot", 'DEF', 4),
    pl('POR', "Matheus Nunes", 'DEF', 5),
    pl('POR', "Nélson Semedo", 'DEF', 6),
    pl('POR', "João Cancelo", 'DEF', 7),
    pl('POR', "Nuno Mendes", 'DEF', 8),
    pl('POR', "Gonçalo Inácio", 'DEF', 9),
    pl('POR', "Renato Veiga", 'DEF', 10),
    pl('POR', "Rúben Dias", 'DEF', 11),
    pl('POR', "Tomás Araújo", 'MED', 12),
    pl('POR', "Rúben Neves", 'MED', 13),
    pl('POR', "Samuel Costa", 'MED', 14),
    pl('POR', "João Neves", 'MED', 15),
    pl('POR', "Vitinha", 'MED', 16),
    pl('POR', "Bruno Fernandes", 'MED', 17),
    pl('POR', "Bernardo Silva", 'MED', 18),
    pl('POR', "João Félix", 'MED', 19),
    pl('POR', "Trincão", 'AVA', 20),
    pl('POR', "Francisco Conceição", 'AVA', 21),
    pl('POR', "Pedro Neto", 'AVA', 22),
    pl('POR', "Rafael Leão", 'AVA', 23),
    pl('POR', "Gonçalo Guedes", 'AVA', 24),
    pl('POR', "Gonçalo Ramos", 'AVA', 25),
    pl('POR', "Cristiano Ronaldo", 'AVA', 26),
  ],
  COD: [
    pl('COD', "Timothy Fayulu", 'GR', 1),
    pl('COD', "Lionel Mpasi", 'GR', 2),
    pl('COD', "Matthieu Epolo", 'GR', 3),
    pl('COD', "Aaron Wan-Bissaka", 'DEF', 4),
    pl('COD', "Gédéon Kalulu", 'DEF', 5),
    pl('COD', "Joris Kayembe", 'DEF', 6),
    pl('COD', "Arthur Masuaku", 'DEF', 7),
    pl('COD', "Steve Kapuadi", 'DEF', 8),
    pl('COD', "Axel Tuanzebe", 'DEF', 9),
    pl('COD', "Chancel Mbemba", 'DEF', 10),
    pl('COD', "Dylan Batubinsika", 'DEF', 11),
    pl('COD', "Noah Sadiki", 'MED', 12),
    pl('COD', "Samuel Moutoussamy", 'MED', 13),
    pl('COD', "Aaron Tshibola", 'MED', 14),
    pl('COD', "Edo Kayembe", 'MED', 15),
    pl('COD', "Ngal'ayel Mukau", 'MED', 16),
    pl('COD', "Charles Pickel", 'MED', 17),
    pl('COD', "Nathanael Mbuku", 'MED', 18),
    pl('COD', "Brian Cipenga", 'MED', 19),
    pl('COD', "Theo Bongonda", 'AVA', 20),
    pl('COD', "Gael Kakuta", 'AVA', 21),
    pl('COD', "Meschack Elia", 'AVA', 22),
    pl('COD', "Fiston Mayele", 'AVA', 23),
    pl('COD', "Cédric Bakambu", 'AVA', 24),
    pl('COD', "Simon Banza", 'AVA', 25),
    pl('COD', "Yoane Wissa", 'AVA', 26),
  ],
  CZE: [
    pl('CZE', "Lukáš Horníček", 'GR', 1),
    pl('CZE', "Matěj Kovář", 'GR', 2),
    pl('CZE', "Jindřich Staněk", 'GR', 3),
    pl('CZE', "Vladimír Coufal", 'DEF', 4),
    pl('CZE', "David Douděra", 'DEF', 5),
    pl('CZE', "Tomáš Holeš", 'DEF', 6),
    pl('CZE', "Robin Hranáč", 'DEF', 7),
    pl('CZE', "Štěpán Chaloupek", 'DEF', 8),
    pl('CZE', "David Jurásek", 'DEF', 9),
    pl('CZE', "Ladislav Krejčí", 'DEF', 10),
    pl('CZE', "Jaroslav Zelený", 'DEF', 11),
    pl('CZE', "David Zima", 'MED', 12),
    pl('CZE', "Lukáš Červ", 'MED', 13),
    pl('CZE', "Vladimír Darida", 'MED', 14),
    pl('CZE', "Lukáš Provod", 'MED', 15),
    pl('CZE', "Michal Sadílek", 'MED', 16),
    pl('CZE', "Hugo Sochůrek", 'MED', 17),
    pl('CZE', "Alexandr Sojka", 'MED', 18),
    pl('CZE', "Tomáš Souček", 'MED', 19),
    pl('CZE', "Pavel Šulc", 'AVA', 20),
    pl('CZE', "Denis Višinský", 'AVA', 21),
    pl('CZE', "Adam Hložek", 'AVA', 22),
    pl('CZE', "Tomáš Chorý", 'AVA', 23),
    pl('CZE', "Mojmír Chytil", 'AVA', 24),
    pl('CZE', "Patrik Schick", 'AVA', 25),
    pl('CZE', "Jan Kuchta", 'AVA', 26),
  ],
  SEN: [
    pl('SEN', "Édouard Mendy", 'GR', 1),
    pl('SEN', "Mory Diaw", 'GR', 2),
    pl('SEN', "Yehvann Diouf", 'GR', 3),
    pl('SEN', "Krépin Diatta", 'DEF', 4),
    pl('SEN', "Antoine Mendy", 'DEF', 5),
    pl('SEN', "Kalidou Koulibaly", 'DEF', 6),
    pl('SEN', "El Hadji Malich Diouf", 'DEF', 7),
    pl('SEN', "Mamadou Sarr", 'DEF', 8),
    pl('SEN', "Moussa Niakhaté", 'DEF', 9),
    pl('SEN', "Abdoulaye Seck", 'DEF', 10),
    pl('SEN', "Ismail Jakobs", 'DEF', 11),
    pl('SEN', "Idrissa Gana Gueye", 'MED', 12),
    pl('SEN', "Pape Gueye", 'MED', 13),
    pl('SEN', "Lamine Camara", 'MED', 14),
    pl('SEN', "Habib Diarra", 'MED', 15),
    pl('SEN', "Pathé Ciss", 'MED', 16),
    pl('SEN', "Pape Matar Sarr", 'MED', 17),
    pl('SEN', "Bara Sapoko Ndiaye", 'MED', 18),
    pl('SEN', "Sadio Mané", 'MED', 19),
    pl('SEN', "Ismaila Sarr", 'AVA', 20),
    pl('SEN', "Iliman Ndiaye", 'AVA', 21),
    pl('SEN', "Assane Diao", 'AVA', 22),
    pl('SEN', "Ibrahim Mbaye", 'AVA', 23),
    pl('SEN', "Nicolas Jackson", 'AVA', 24),
    pl('SEN', "Bamba Dieng", 'AVA', 25),
    pl('SEN', "Chérif Ndiaye", 'AVA', 26),
  ],
  SWE: [
    pl('SWE', "Viktor Johansson", 'GR', 1),
    pl('SWE', "Kristoffer Nordfeldt", 'GR', 2),
    pl('SWE', "Jacob Widell Zetterström", 'GR', 3),
    pl('SWE', "Hjalmar Ekdal", 'DEF', 4),
    pl('SWE', "Gabriel Gudmundsson", 'DEF', 5),
    pl('SWE', "Isak Hien", 'DEF', 6),
    pl('SWE', "Herman Johansson", 'DEF', 7),
    pl('SWE', "Gustaf Lagerbielke", 'DEF', 8),
    pl('SWE', "Victor Nilsson Lindelöf", 'DEF', 9),
    pl('SWE', "Eric Smith", 'DEF', 10),
    pl('SWE', "Carl Starfelt", 'DEF', 11),
    pl('SWE', "Elliot Stroud", 'MED', 12),
    pl('SWE', "Daniel Svensson", 'MED', 13),
    pl('SWE', "Taha Ali", 'MED', 14),
    pl('SWE', "Yasin Ayari", 'MED', 15),
    pl('SWE', "Lucas Bergvall", 'MED', 16),
    pl('SWE', "Alexander Bernhardsson", 'MED', 17),
    pl('SWE', "Anthony Elanga", 'MED', 18),
    pl('SWE', "Viktor Gyökeres", 'MED', 19),
    pl('SWE', "Alexander Isak", 'AVA', 20),
    pl('SWE', "Jesper Karlström", 'AVA', 21),
    pl('SWE', "Gustaf Nilsson", 'AVA', 22),
    pl('SWE', "Benjamin Nygren", 'AVA', 23),
    pl('SWE', "Ken Sema", 'AVA', 24),
    pl('SWE', "Mattias Svanberg", 'AVA', 25),
    pl('SWE', "Besfort Zeneli", 'AVA', 26),
  ],
  SUI: [
    pl('SUI', "Marvin Keller", 'GR', 1),
    pl('SUI', "Gregor Kobel", 'GR', 2),
    pl('SUI', "Yvon Mvogo", 'GR', 3),
    pl('SUI', "Manuel Akanji", 'DEF', 4),
    pl('SUI', "Aurèle Amenda", 'DEF', 5),
    pl('SUI', "Eray Comert", 'DEF', 6),
    pl('SUI', "Nico Elvedi", 'DEF', 7),
    pl('SUI', "Luca Jaquez", 'DEF', 8),
    pl('SUI', "Miro Muheim", 'DEF', 9),
    pl('SUI', "Ricardo Rodriguez", 'DEF', 10),
    pl('SUI', "Silvan Widmer", 'DEF', 11),
    pl('SUI', "Michel Aebischer", 'MED', 12),
    pl('SUI', "Zeki Amdouni", 'MED', 13),
    pl('SUI', "Breel Embolo", 'MED', 14),
    pl('SUI', "Christian Fassnacht", 'MED', 15),
    pl('SUI', "Remo Freuler", 'MED', 16),
    pl('SUI', "Cedric Itten", 'MED', 17),
    pl('SUI', "Ardon Jashari", 'MED', 18),
    pl('SUI', "Johan Manzambi", 'MED', 19),
    pl('SUI', "Dan Ndoye", 'AVA', 20),
    pl('SUI', "Noah Okafor", 'AVA', 21),
    pl('SUI', "Fabian Rieder", 'AVA', 22),
    pl('SUI', "Djibril Sow", 'AVA', 23),
    pl('SUI', "Ruben Vargas", 'AVA', 24),
    pl('SUI', "Grant Xhaka", 'AVA', 25),
    pl('SUI', "Denis Zakaria", 'AVA', 26),
  ],
  TUN: [
    pl('TUN', "Dahmen", 'GR', 1),
    pl('TUN', "Chamakh", 'GR', 2),
    pl('TUN', "Ben Hassen", 'GR', 3),
    pl('TUN', "Valery", 'DEF', 4),
    pl('TUN', "Neffati", 'DEF', 5),
    pl('TUN', "Bronn", 'DEF', 6),
    pl('TUN', "Talbi", 'DEF', 7),
    pl('TUN', "Rekik", 'DEF', 8),
    pl('TUN', "Arous", 'DEF', 9),
    pl('TUN', "Chikhaoui", 'DEF', 10),
    pl('TUN', "Abdi", 'DEF', 11),
    pl('TUN', "Ben Hmida", 'MED', 12),
    pl('TUN', "Skhiri", 'MED', 13),
    pl('TUN', "Mahmoud", 'MED', 14),
    pl('TUN', "Khedira", 'MED', 15),
    pl('TUN', "Ben Silmane", 'MED', 16),
    pl('TUN', "Ben Ouanes", 'MED', 17),
    pl('TUN', "Gharbi", 'MED', 18),
    pl('TUN', "Hannibal", 'MED', 19),
    pl('TUN', "Ayari", 'AVA', 20),
    pl('TUN', "Achouri", 'AVA', 21),
    pl('TUN', "Saad", 'AVA', 22),
    pl('TUN', "Chaouat", 'AVA', 23),
    pl('TUN', "Mastoui", 'AVA', 24),
    pl('TUN', "Elloumi", 'AVA', 25),
    pl('TUN', "Tonekti", 'AVA', 26),
  ],
  TUR: [
    pl('TUR', "Altay Bayindir", 'GR', 1),
    pl('TUR', "Mert Günok", 'GR', 2),
    pl('TUR', "Ugurcan Cakir", 'GR', 3),
    pl('TUR', "Abdulkerim Bardakci", 'DEF', 4),
    pl('TUR', "Caglar Soyuncu", 'DEF', 5),
    pl('TUR', "Eren Elmalı", 'DEF', 6),
    pl('TUR', "Ferdi Kadıoğlu", 'DEF', 7),
    pl('TUR', "Merih Demiral", 'DEF', 8),
    pl('TUR', "Mert Müldür", 'DEF', 9),
    pl('TUR', "Ozan Kabak", 'DEF', 10),
    pl('TUR', "Samet Akaydin", 'DEF', 11),
    pl('TUR', "Zeki Celik", 'MED', 12),
    pl('TUR', "Hakan Calhanoglu", 'MED', 13),
    pl('TUR', "Ismail Yuksek", 'MED', 14),
    pl('TUR', "Kaan Ayhan", 'MED', 15),
    pl('TUR', "Orkun Kökçü", 'MED', 16),
    pl('TUR', "Salih Ozcan", 'MED', 17),
    pl('TUR', "Arda Güler", 'MED', 18),
    pl('TUR', "Barış Alper Yılmaz", 'MED', 19),
    pl('TUR', "Can Uzun", 'AVA', 20),
    pl('TUR', "Deniz Gül", 'AVA', 21),
    pl('TUR', "Irfan Can Kahveci", 'AVA', 22),
    pl('TUR', "Kenan Yıldız", 'AVA', 23),
    pl('TUR', "Kerem Akturkoglu", 'AVA', 24),
    pl('TUR', "Oguz Aydin", 'AVA', 25),
    pl('TUR', "Yunus Akgun", 'AVA', 26),
  ],
  URU: [
    pl('URU', "Sergio Rochet", 'GR', 1),
    pl('URU', "Fernando Muslera", 'GR', 2),
    pl('URU', "Santiago Mele", 'GR', 3),
    pl('URU', "Guillermo Varela", 'DEF', 4),
    pl('URU', "Ronald Araujo", 'DEF', 5),
    pl('URU', "José María Giménez", 'DEF', 6),
    pl('URU', "Santiago Bueno", 'DEF', 7),
    pl('URU', "Sebastián Cáceres", 'DEF', 8),
    pl('URU', "Mathías Olivera", 'DEF', 9),
    pl('URU', "Joaquín Piquerez", 'DEF', 10),
    pl('URU', "Matías Viña", 'DEF', 11),
    pl('URU', "Manuel Ugarte", 'MED', 12),
    pl('URU', "Emiliano Martínez", 'MED', 13),
    pl('URU', "Rodrigo Bentancur", 'MED', 14),
    pl('URU', "Federico Valverde", 'MED', 15),
    pl('URU', "Agustín Canobbio", 'MED', 16),
    pl('URU', "Juan Manuel Sanabria", 'MED', 17),
    pl('URU', "Giorgian De Arrascaeta", 'MED', 18),
    pl('URU', "Nicolás de la Cruz", 'MED', 19),
    pl('URU', "Rodrigo Zalazar", 'AVA', 20),
    pl('URU', "Facundo Pellistri", 'AVA', 21),
    pl('URU', "Maximiliano Araújo", 'AVA', 22),
    pl('URU', "Brian Rodríguez", 'AVA', 23),
    pl('URU', "Rodrigo Aguirre", 'AVA', 24),
    pl('URU', "Federico Viñas", 'AVA', 25),
    pl('URU', "Darwin Núñez", 'AVA', 26),
  ],
  UZB: [
    pl('UZB', "Otkir Yusupov", 'GR', 1),
    pl('UZB', "Abduvohid Nematov", 'GR', 2),
    pl('UZB', "Botirali Ergashev", 'GR', 3),
    pl('UZB', "Abdukodir Husanov", 'DEF', 4),
    pl('UZB', "Hojiakbar Alijonov", 'DEF', 5),
    pl('UZB', "Farruh Sayfiyev", 'DEF', 6),
    pl('UZB', "Rustam Ashurmatov", 'DEF', 7),
    pl('UZB', "Umar Eshmurodov", 'DEF', 8),
    pl('UZB', "Sherzod Nasrullayev", 'DEF', 9),
    pl('UZB', "Abdulla Abdullayev", 'DEF', 10),
    pl('UZB', "Avazbek Olmasaliyev", 'DEF', 11),
    pl('UZB', "Jahongir Orozov", 'MED', 12),
    pl('UZB', "Behruz Karimov", 'MED', 13),
    pl('UZB', "Akmal Mozgovoy", 'MED', 14),
    pl('UZB', "Otabek Shukurov", 'MED', 15),
    pl('UZB', "Jamshid Iskanderov", 'MED', 16),
    pl('UZB', "Odil Hamrobekov", 'MED', 17),
    pl('UZB', "Ruslanbek Jiyanov", 'MED', 18),
    pl('UZB', "Oston O'runov", 'MED', 19),
    pl('UZB', "Dostonbek Hamdamov", 'AVA', 20),
    pl('UZB', "Aziz G'aniyev", 'AVA', 21),
    pl('UZB', "Abbosbek Fayzullayev", 'AVA', 22),
    pl('UZB', "Sherzod Esanov", 'AVA', 23),
    pl('UZB', "Eldor Shomurodov", 'AVA', 24),
    pl('UZB', "Igor Sergeyev", 'AVA', 25),
    pl('UZB', "Azizbek Omonov", 'AVA', 26),
  ],
};
