/** Plantéis reais (indicativos) das seleções do Mundial 2026 — candidatos a escolher. */
import type { Footballer, Pos } from './types';

function pl(team: string, name: string, pos: Pos, number: number): Footballer {
  return { id: `${team}-${number}`, name, team, pos, number };
}

export const EXTRA_SQUADS: Record<string, Footballer[]> = {
  AUS: [
    pl('AUS', 'Mat Ryan', 'GR', 1),
    pl('AUS', 'Joe Gauci', 'GR', 18),
    pl('AUS', 'Paul Izzo', 'GR', 23),
    pl('AUS', 'Harry Souttar', 'DEF', 19),
    pl('AUS', 'Kye Rowles', 'DEF', 4),
    pl('AUS', 'Cameron Burgess', 'DEF', 14),
    pl('AUS', 'Aziz Behich', 'DEF', 16),
    pl('AUS', 'Nathaniel Atkinson', 'DEF', 2),
    pl('AUS', 'Jordan Bos', 'DEF', 5),
    pl('AUS', 'Lewis Miller', 'DEF', 3),
    pl('AUS', 'Aiden O’Neill', 'MED', 13),
    pl('AUS', 'Connor Metcalfe', 'MED', 8),
    pl('AUS', 'Jackson Irvine', 'MED', 22),
    pl('AUS', 'Riley McGree', 'MED', 17),
    pl('AUS', 'Keanu Baccus', 'MED', 6),
    pl('AUS', 'Ajdin Hrustic', 'MED', 10),
    pl('AUS', 'Mathew Leckie', 'AVA', 7),
    pl('AUS', 'Craig Goodwin', 'AVA', 11),
    pl('AUS', 'Kusini Yengi', 'AVA', 9),
    pl('AUS', 'Mitchell Duke', 'AVA', 15),
    pl('AUS', 'Nestory Irankunda', 'AVA', 20),
  ],
  SCO: [
    pl('SCO', 'Angus Gunn', 'GR', 1),
    pl('SCO', 'Craig Gordon', 'GR', 12),
    pl('SCO', 'Zander Clark', 'GR', 23),
    pl('SCO', 'Andrew Robertson', 'DEF', 3),
    pl('SCO', 'Kieran Tierney', 'DEF', 6),
    pl('SCO', 'Jack Hendry', 'DEF', 4),
    pl('SCO', 'Grant Hanley', 'DEF', 5),
    pl('SCO', 'Scott McKenna', 'DEF', 2),
    pl('SCO', 'Anthony Ralston', 'DEF', 16),
    pl('SCO', 'Aaron Hickey', 'DEF', 18),
    pl('SCO', 'Callum McGregor', 'MED', 8),
    pl('SCO', 'Billy Gilmour', 'MED', 15),
    pl('SCO', 'Scott McTominay', 'MED', 7),
    pl('SCO', 'John McGinn', 'MED', 10),
    pl('SCO', 'Ryan Christie', 'MED', 11),
    pl('SCO', 'Stuart Armstrong', 'MED', 17),
    pl('SCO', 'Che Adams', 'AVA', 9),
    pl('SCO', 'Lyndon Dykes', 'AVA', 13),
    pl('SCO', 'Lawrence Shankland', 'AVA', 20),
    pl('SCO', 'Ben Doak', 'AVA', 22),
    pl('SCO', 'James Forrest', 'AVA', 19),
  ],
  MAR: [
    pl('MAR', 'Yassine Bounou', 'GR', 1),
    pl('MAR', 'Munir El Kajoui', 'GR', 12),
    pl('MAR', 'Mehdi Benabid', 'GR', 23),
    pl('MAR', 'Achraf Hakimi', 'DEF', 2),
    pl('MAR', 'Noussair Mazraoui', 'DEF', 3),
    pl('MAR', 'Romain Saïss', 'DEF', 6),
    pl('MAR', 'Nayef Aguerd', 'DEF', 5),
    pl('MAR', 'Jawad El Yamiq', 'DEF', 18),
    pl('MAR', 'Achraf Dari', 'DEF', 22),
    pl('MAR', 'Yahya Attiat-Allah', 'DEF', 21),
    pl('MAR', 'Sofyan Amrabat', 'MED', 4),
    pl('MAR', 'Azzedine Ounahi', 'MED', 8),
    pl('MAR', 'Bilal El Khannouss', 'MED', 15),
    pl('MAR', 'Amir Richardson', 'MED', 17),
    pl('MAR', 'Selim Amallah', 'MED', 13),
    pl('MAR', 'Brahim Díaz', 'MED', 19),
    pl('MAR', 'Hakim Ziyech', 'AVA', 7),
    pl('MAR', 'Sofiane Boufal', 'AVA', 10),
    pl('MAR', 'Youssef En-Nesyri', 'AVA', 9),
    pl('MAR', 'Ayoub El Kaabi', 'AVA', 11),
    pl('MAR', 'Abde Ezzalzouli', 'AVA', 14),
  ],
  HAI: [
    pl('HAI', 'Johny Placide', 'GR', 1),
    pl('HAI', 'Josué Duverger', 'GR', 16),
    pl('HAI', 'Alexandre Pierre', 'GR', 23),
    pl('HAI', 'Ricardo Adé', 'DEF', 3),
    pl('HAI', 'Carlens Arcus', 'DEF', 2),
    pl('HAI', 'Jems Geffrard', 'DEF', 5),
    pl('HAI', 'Andrew Jean-Baptiste', 'DEF', 4),
    pl('HAI', 'Garven Metusala', 'DEF', 6),
    pl('HAI', 'Christopher Attys', 'DEF', 13),
    pl('HAI', 'Zachary Herivaux', 'DEF', 14),
    pl('HAI', 'Danley Jean Jacques', 'MED', 8),
    pl('HAI', 'Carl Sainté', 'MED', 18),
    pl('HAI', 'Leverton Pierre', 'MED', 17),
    pl('HAI', 'Derrick Etienne', 'MED', 10),
    pl('HAI', 'Steeven Saba', 'MED', 15),
    pl('HAI', 'Bryan Alceus', 'MED', 20),
    pl('HAI', 'Frantzdy Pierrot', 'AVA', 9),
    pl('HAI', 'Duckens Nazon', 'AVA', 7),
    pl('HAI', 'Don Deedson Louicius', 'AVA', 11),
    pl('HAI', 'Ruben Providence', 'AVA', 19),
    pl('HAI', 'Jean-Kévin Augustin', 'AVA', 21),
  ],
  TUR: [
    pl('TUR', 'Altay Bayındır', 'GR', 1),
    pl('TUR', 'Uğurcan Çakır', 'GR', 23),
    pl('TUR', 'Mert Günok', 'GR', 12),
    pl('TUR', 'Zeki Çelik', 'DEF', 2),
    pl('TUR', 'Merih Demiral', 'DEF', 3),
    pl('TUR', 'Kaan Ayhan', 'DEF', 4),
    pl('TUR', 'Abdülkerim Bardakcı', 'DEF', 5),
    pl('TUR', 'Samet Akaydın', 'DEF', 14),
    pl('TUR', 'Ferdi Kadıoğlu', 'DEF', 20),
    pl('TUR', 'Mert Müldür', 'DEF', 22),
    pl('TUR', 'Hakan Çalhanoğlu', 'MED', 10),
    pl('TUR', 'İsmail Yüksek', 'MED', 6),
    pl('TUR', 'Salih Özcan', 'MED', 8),
    pl('TUR', 'Orkun Kökçü', 'MED', 13),
    pl('TUR', 'Arda Güler', 'MED', 21),
    pl('TUR', 'Kenan Yıldız', 'MED', 7),
    pl('TUR', 'Kerem Aktürkoğlu', 'AVA', 11),
    pl('TUR', 'Yusuf Yazıcı', 'AVA', 17),
    pl('TUR', 'Barış Alper Yılmaz', 'AVA', 9),
    pl('TUR', 'Cenk Tosun', 'AVA', 18),
    pl('TUR', 'Semih Kılıçsoy', 'AVA', 19),
  ],
  PAR: [
    pl('PAR', 'Antony Silva', 'GR', 1),
    pl('PAR', 'Roberto Fernández', 'GR', 12),
    pl('PAR', 'Gaspar Servio', 'GR', 23),
    pl('PAR', 'Gustavo Gómez', 'DEF', 2),
    pl('PAR', 'Omar Alderete', 'DEF', 3),
    pl('PAR', 'Fabián Balbuena', 'DEF', 4),
    pl('PAR', 'Junior Alonso', 'DEF', 6),
    pl('PAR', 'Juan Cáceres', 'DEF', 13),
    pl('PAR', 'Agustín Sández', 'DEF', 16),
    pl('PAR', 'Damián Bobadilla', 'DEF', 22),
    pl('PAR', 'Andrés Cubas', 'MED', 5),
    pl('PAR', 'Mathías Villasanti', 'MED', 8),
    pl('PAR', 'Diego Gómez', 'MED', 15),
    pl('PAR', 'Julio Enciso', 'MED', 10),
    pl('PAR', 'Miguel Almirón', 'MED', 7),
    pl('PAR', 'Ramón Sosa', 'MED', 11),
    pl('PAR', 'Antonio Sanabria', 'AVA', 9),
    pl('PAR', 'Adam Bareiro', 'AVA', 19),
    pl('PAR', 'Gabriel Ávalos', 'AVA', 18),
    pl('PAR', 'Alex Arce', 'AVA', 14),
    pl('PAR', 'Ángel Romero', 'AVA', 20),
  ],
  SWE: [
    pl('SWE', 'Robin Olsen', 'GR', 1),
    pl('SWE', 'Kristoffer Nordfeldt', 'GR', 12),
    pl('SWE', 'Viktor Johansson', 'GR', 23),
    pl('SWE', 'Victor Lindelöf', 'DEF', 3),
    pl('SWE', 'Isak Hien', 'DEF', 5),
    pl('SWE', 'Gabriel Gudmundsson', 'DEF', 2),
    pl('SWE', 'Emil Krafth', 'DEF', 4),
    pl('SWE', 'Hjalmar Ekdal', 'DEF', 14),
    pl('SWE', 'Daniel Svensson', 'DEF', 16),
    pl('SWE', 'Jens Cajuste', 'MED', 8),
    pl('SWE', 'Hugo Larsson', 'MED', 6),
    pl('SWE', 'Mattias Svanberg', 'MED', 7),
    pl('SWE', 'Albin Ekdal', 'MED', 10),
    pl('SWE', 'Yasin Ayari', 'MED', 15),
    pl('SWE', 'Anton Salétros', 'MED', 17),
    pl('SWE', 'Alexander Isak', 'AVA', 9),
    pl('SWE', 'Viktor Gyökeres', 'AVA', 11),
    pl('SWE', 'Dejan Kulusevski', 'AVA', 21),
    pl('SWE', 'Anthony Elanga', 'AVA', 18),
    pl('SWE', 'Emil Forsberg', 'AVA', 20),
    pl('SWE', 'Jesper Karlsson', 'AVA', 19),
  ],
  GER: [
    pl('GER', 'Manuel Neuer', 'GR', 1),
    pl('GER', 'Marc-André ter Stegen', 'GR', 22),
    pl('GER', 'Oliver Baumann', 'GR', 12),
    pl('GER', 'Joshua Kimmich', 'DEF', 6),
    pl('GER', 'Antonio Rüdiger', 'DEF', 2),
    pl('GER', 'Jonathan Tah', 'DEF', 4),
    pl('GER', 'Nico Schlotterbeck', 'DEF', 23),
    pl('GER', 'David Raum', 'DEF', 3),
    pl('GER', 'Maximilian Mittelstädt', 'DEF', 18),
    pl('GER', 'Waldemar Anton', 'DEF', 5),
    pl('GER', 'Toni Kroos', 'MED', 8),
    pl('GER', 'İlkay Gündoğan', 'MED', 21),
    pl('GER', 'Robert Andrich', 'MED', 16),
    pl('GER', 'Jamal Musiala', 'MED', 10),
    pl('GER', 'Florian Wirtz', 'MED', 17),
    pl('GER', 'Pascal Groß', 'MED', 13),
    pl('GER', 'Kai Havertz', 'AVA', 7),
    pl('GER', 'Niclas Füllkrug', 'AVA', 9),
    pl('GER', 'Leroy Sané', 'AVA', 19),
    pl('GER', 'Maximilian Beier', 'AVA', 14),
    pl('GER', 'Deniz Undav', 'AVA', 15),
  ],
  CIV: [
    pl('CIV', 'Yahia Fofana', 'GR', 1),
    pl('CIV', 'Mohamed Koné', 'GR', 16),
    pl('CIV', 'Charles Folly', 'GR', 23),
    pl('CIV', 'Serge Aurier', 'DEF', 2),
    pl('CIV', 'Ghislain Konan', 'DEF', 3),
    pl('CIV', 'Willy Boly', 'DEF', 22),
    pl('CIV', 'Evan Ndicka', 'DEF', 4),
    pl('CIV', 'Odilon Kossounou', 'DEF', 5),
    pl('CIV', 'Wilfried Singo', 'DEF', 6),
    pl('CIV', 'Ousmane Diomandé', 'DEF', 21),
    pl('CIV', 'Franck Kessié', 'MED', 8),
    pl('CIV', 'Ibrahim Sangaré', 'MED', 13),
    pl('CIV', 'Seko Fofana', 'MED', 17),
    pl('CIV', 'Jean-Michaël Seri', 'MED', 18),
    pl('CIV', 'Hamed Traorè', 'MED', 14),
    pl('CIV', 'Simon Adingra', 'MED', 7),
    pl('CIV', 'Sébastien Haller', 'AVA', 9),
    pl('CIV', 'Nicolas Pépé', 'AVA', 10),
    pl('CIV', 'Jonathan Bamba', 'AVA', 11),
    pl('CIV', 'Christian Kouamé', 'AVA', 15),
    pl('CIV', 'Amad Diallo', 'AVA', 19),
  ],
  ECU: [
    pl('ECU', 'Hernán Galíndez', 'GR', 1),
    pl('ECU', 'Alexander Domínguez', 'GR', 12),
    pl('ECU', 'Gonzalo Valle', 'GR', 23),
    pl('ECU', 'Pervis Estupiñán', 'DEF', 7),
    pl('ECU', 'Piero Hincapié', 'DEF', 3),
    pl('ECU', 'Félix Torres', 'DEF', 4),
    pl('ECU', 'William Pacho', 'DEF', 5),
    pl('ECU', 'Ángelo Preciado', 'DEF', 17),
    pl('ECU', 'Joel Ordóñez', 'DEF', 22),
    pl('ECU', 'Xavier Arreaga', 'DEF', 2),
    pl('ECU', 'Moisés Caicedo', 'MED', 8),
    pl('ECU', 'Alan Franco', 'MED', 6),
    pl('ECU', 'Jhegson Méndez', 'MED', 20),
    pl('ECU', 'Kendry Páez', 'MED', 10),
    pl('ECU', 'Patrik Mercado', 'MED', 16),
    pl('ECU', 'Alan Minda', 'MED', 15),
    pl('ECU', 'Enner Valencia', 'AVA', 13),
    pl('ECU', 'Gonzalo Plata', 'AVA', 11),
    pl('ECU', 'Kevin Rodríguez', 'AVA', 9),
    pl('ECU', 'Jeremy Sarmiento', 'AVA', 19),
    pl('ECU', 'John Yeboah', 'AVA', 14),
  ],
  CUW: [
    pl('CUW', 'Eloy Room', 'GR', 1),
    pl('CUW', 'Tyrick Bodak', 'GR', 12),
    pl('CUW', 'Kenji Gorré', 'GR', 23),
    pl('CUW', 'Cuco Martina', 'DEF', 2),
    pl('CUW', 'Juninho Bacuna', 'DEF', 6),
    pl('CUW', 'Shurandy Sambo', 'DEF', 3),
    pl('CUW', 'Roshon van Eijma', 'DEF', 4),
    pl('CUW', 'Sherel Floranus', 'DEF', 5),
    pl('CUW', 'Armando Obispo', 'DEF', 13),
    pl('CUW', 'Rangelo Janga', 'DEF', 14),
    pl('CUW', 'Leandro Bacuna', 'MED', 8),
    pl('CUW', 'Jurién Gaari', 'MED', 16),
    pl('CUW', 'Sontje Hansen', 'MED', 17),
    pl('CUW', 'Tahith Chong', 'MED', 10),
    pl('CUW', 'Brandley Kuwas', 'MED', 7),
    pl('CUW', 'Jeremy Antonisse', 'MED', 15),
    pl('CUW', 'Gervane Kastaneer', 'AVA', 9),
    pl('CUW', 'Jean-Carlos Bisswane', 'AVA', 11),
    pl('CUW', 'Kenji Martijn', 'AVA', 18),
    pl('CUW', 'Livano Comenencia', 'AVA', 19),
    pl('CUW', 'Ricardo Kishna', 'AVA', 20),
  ],
  TUN: [
    pl('TUN', 'Aymen Dahmen', 'GR', 1),
    pl('TUN', 'Mouez Hassen', 'GR', 16),
    pl('TUN', 'Béchir Ben Saïd', 'GR', 23),
    pl('TUN', 'Montassar Talbi', 'DEF', 4),
    pl('TUN', 'Yassine Meriah', 'DEF', 3),
    pl('TUN', 'Dylan Bronn', 'DEF', 5),
    pl('TUN', 'Ali Abdi', 'DEF', 2),
    pl('TUN', 'Mohamed Dräger', 'DEF', 22),
    pl('TUN', 'Wajdi Kechrida', 'DEF', 17),
    pl('TUN', 'Yan Valery', 'DEF', 21),
    pl('TUN', 'Aïssa Laïdouni', 'MED', 14),
    pl('TUN', 'Ellyes Skhiri', 'MED', 6),
    pl('TUN', 'Hannibal Mejbri', 'MED', 8),
    pl('TUN', 'Ferjani Sassi', 'MED', 13),
    pl('TUN', 'Mohamed Ali Ben Romdhane', 'MED', 15),
    pl('TUN', 'Anis Ben Slimane', 'MED', 18),
    pl('TUN', 'Youssef Msakni', 'AVA', 7),
    pl('TUN', 'Naïm Sliti', 'AVA', 10),
    pl('TUN', 'Seifeddine Jaziri', 'AVA', 9),
    pl('TUN', 'Elias Saad', 'AVA', 11),
    pl('TUN', 'Hazem Mastouri', 'AVA', 19),
  ],
  JPN: [
    pl('JPN', 'Zion Suzuki', 'GR', 1),
    pl('JPN', 'Daniel Schmidt', 'GR', 12),
    pl('JPN', 'Keisuke Osako', 'GR', 23),
    pl('JPN', 'Takehiro Tomiyasu', 'DEF', 16),
    pl('JPN', 'Ko Itakura', 'DEF', 22),
    pl('JPN', 'Shogo Taniguchi', 'DEF', 4),
    pl('JPN', 'Hiroki Ito', 'DEF', 3),
    pl('JPN', 'Yukinari Sugawara', 'DEF', 19),
    pl('JPN', 'Hiroki Sakai', 'DEF', 2),
    pl('JPN', 'Daichi Hayashi', 'DEF', 5),
    pl('JPN', 'Wataru Endo', 'MED', 6),
    pl('JPN', 'Hidemasa Morita', 'MED', 13),
    pl('JPN', 'Ao Tanaka', 'MED', 17),
    pl('JPN', 'Takefusa Kubo', 'MED', 8),
    pl('JPN', 'Ritsu Doan', 'MED', 11),
    pl('JPN', 'Kaoru Mitoma', 'MED', 14),
    pl('JPN', 'Junya Ito', 'AVA', 9),
    pl('JPN', 'Daizen Maeda', 'AVA', 15),
    pl('JPN', 'Ayase Ueda', 'AVA', 20),
    pl('JPN', 'Takumi Minamino', 'AVA', 10),
    pl('JPN', 'Keito Nakamura', 'AVA', 7),
  ],
  KSA: [
    pl('KSA', 'Mohammed Al-Owais', 'GR', 21),
    pl('KSA', 'Nawaf Al-Aqidi', 'GR', 1),
    pl('KSA', 'Ahmed Al-Kassar', 'GR', 22),
    pl('KSA', 'Saud Abdulhamid', 'DEF', 2),
    pl('KSA', 'Sultan Al-Ghannam', 'DEF', 13),
    pl('KSA', 'Hassan Tambakti', 'DEF', 3),
    pl('KSA', 'Ali Al-Bulaihi', 'DEF', 4),
    pl('KSA', 'Abdulelah Al-Amri', 'DEF', 5),
    pl('KSA', 'Yasser Al-Shahrani', 'DEF', 12),
    pl('KSA', 'Saud Abdulhamid II', 'DEF', 6),
    pl('KSA', 'Mohamed Kanno', 'MED', 23),
    pl('KSA', 'Nasser Al-Dawsari', 'MED', 17),
    pl('KSA', 'Sami Al-Najei', 'MED', 7),
    pl('KSA', 'Musab Al-Juwayr', 'MED', 8),
    pl('KSA', 'Abdullah Otayf', 'MED', 14),
    pl('KSA', 'Ali Lajami', 'MED', 16),
    pl('KSA', 'Salem Al-Dawsari', 'AVA', 10),
    pl('KSA', 'Firas Al-Buraikan', 'AVA', 9),
    pl('KSA', 'Saleh Al-Shehri', 'AVA', 11),
    pl('KSA', 'Abdullah Al-Hamdan', 'AVA', 20),
    pl('KSA', 'Marwan Al-Sahafi', 'AVA', 19),
  ],
  BEL: [
    pl('BEL', 'Koen Casteels', 'GR', 1),
    pl('BEL', 'Matz Sels', 'GR', 12),
    pl('BEL', 'Thomas Kaminski', 'GR', 16),
    pl('BEL', 'Wout Faes', 'DEF', 4),
    pl('BEL', 'Zeno Debast', 'DEF', 3),
    pl('BEL', 'Jan Vertonghen', 'DEF', 5),
    pl('BEL', 'Timothy Castagne', 'DEF', 21),
    pl('BEL', 'Arthur Theate', 'DEF', 24),
    pl('BEL', 'Maxim De Cuyper', 'DEF', 15),
    pl('BEL', 'Koni De Winter', 'DEF', 2),
    pl('BEL', 'Youri Tielemans', 'MED', 8),
    pl('BEL', 'Amadou Onana', 'MED', 6),
    pl('BEL', 'Orel Mangala', 'MED', 18),
    pl('BEL', 'Kevin De Bruyne', 'MED', 7),
    pl('BEL', 'Charles De Ketelaere', 'MED', 17),
    pl('BEL', 'Arthur Vermeeren', 'MED', 20),
    pl('BEL', 'Jérémy Doku', 'AVA', 22),
    pl('BEL', 'Leandro Trossard', 'AVA', 11),
    pl('BEL', 'Romelu Lukaku', 'AVA', 9),
    pl('BEL', 'Loïs Openda', 'AVA', 10),
    pl('BEL', 'Dodi Lukebakio', 'AVA', 14),
  ],
  IRN: [
    pl('IRN', 'Alireza Beiranvand', 'GR', 1),
    pl('IRN', 'Payam Niazmand', 'GR', 22),
    pl('IRN', 'Hossein Hosseini', 'GR', 12),
    pl('IRN', 'Sadegh Moharrami', 'DEF', 2),
    pl('IRN', 'Shojae Khalilzadeh', 'DEF', 4),
    pl('IRN', 'Majid Hosseini', 'DEF', 5),
    pl('IRN', 'Aref Aghasi', 'DEF', 3),
    pl('IRN', 'Milad Mohammadi', 'DEF', 13),
    pl('IRN', 'Ramin Rezaeian', 'DEF', 23),
    pl('IRN', 'Hossein Kanaanizadegan', 'DEF', 8),
    pl('IRN', 'Saeid Ezatolahi', 'MED', 6),
    pl('IRN', 'Ahmad Nourollahi', 'MED', 18),
    pl('IRN', 'Saman Ghoddos', 'MED', 21),
    pl('IRN', 'Mehdi Ghayedi', 'MED', 11),
    pl('IRN', 'Alireza Jahanbakhsh', 'MED', 7),
    pl('IRN', 'Ali Gholizadeh', 'MED', 17),
    pl('IRN', 'Mehdi Taremi', 'AVA', 9),
    pl('IRN', 'Sardar Azmoun', 'AVA', 20),
    pl('IRN', 'Karim Ansarifard', 'AVA', 10),
    pl('IRN', 'Shahab Zahedi', 'AVA', 14),
    pl('IRN', 'Mohammad Mohebi', 'AVA', 19),
  ],
  URU: [
    pl('URU', 'Sergio Rochet', 'GR', 1),
    pl('URU', 'Santiago Mele', 'GR', 12),
    pl('URU', 'Franco Israel', 'GR', 23),
    pl('URU', 'Ronald Araújo', 'DEF', 4),
    pl('URU', 'José María Giménez', 'DEF', 2),
    pl('URU', 'Sebastián Cáceres', 'DEF', 3),
    pl('URU', 'Mathías Olivera', 'DEF', 17),
    pl('URU', 'Nahitan Nández', 'DEF', 16),
    pl('URU', 'Guillermo Varela', 'DEF', 22),
    pl('URU', 'Santiago Bueno', 'DEF', 19),
    pl('URU', 'Federico Valverde', 'MED', 15),
    pl('URU', 'Manuel Ugarte', 'MED', 5),
    pl('URU', 'Rodrigo Bentancur', 'MED', 6),
    pl('URU', 'Nicolás de la Cruz', 'MED', 10),
    pl('URU', 'Giorgian de Arrascaeta', 'MED', 8),
    pl('URU', 'Maximiliano Araújo', 'MED', 11),
    pl('URU', 'Darwin Núñez', 'AVA', 9),
    pl('URU', 'Facundo Pellistri', 'AVA', 7),
    pl('URU', 'Brian Rodríguez', 'AVA', 20),
    pl('URU', 'Rodrigo Aguirre', 'AVA', 18),
    pl('URU', 'Cristian Olivera', 'AVA', 21),
  ],
  CPV: [
    pl('CPV', 'Vozinha', 'GR', 1),
    pl('CPV', 'Bruno Varela', 'GR', 12),
    pl('CPV', 'Márcio Rosa', 'GR', 23),
    pl('CPV', 'Diney', 'DEF', 2),
    pl('CPV', 'Stopira', 'DEF', 3),
    pl('CPV', 'Roberto Lopes', 'DEF', 4),
    pl('CPV', 'Steven Moreira', 'DEF', 5),
    pl('CPV', 'Logan Costa', 'DEF', 6),
    pl('CPV', 'Kenny Rocha Santos', 'DEF', 13),
    pl('CPV', 'Dylan Tavares', 'DEF', 14),
    pl('CPV', 'Jamiro Monteiro', 'MED', 8),
    pl('CPV', 'Kevin Pina', 'MED', 7),
    pl('CPV', 'Deroy Duarte', 'MED', 17),
    pl('CPV', 'Laros Duarte', 'MED', 15),
    pl('CPV', 'Telmo Arcanjo', 'MED', 18),
    pl('CPV', 'Patrick Andrade', 'MED', 16),
    pl('CPV', 'Ryan Mendes', 'AVA', 10),
    pl('CPV', 'Garry Rodrigues', 'AVA', 11),
    pl('CPV', 'Bebé', 'AVA', 9),
    pl('CPV', 'Gilson Tavares', 'AVA', 19),
    pl('CPV', 'Willy Semedo', 'AVA', 20),
  ],
  NZL: [
    pl('NZL', 'Max Crocombe', 'GR', 1),
    pl('NZL', 'Alex Paulsen', 'GR', 12),
    pl('NZL', 'Oliver Sail', 'GR', 23),
    pl('NZL', 'Tim Payne', 'DEF', 2),
    pl('NZL', 'Michael Boxall', 'DEF', 3),
    pl('NZL', 'Nando Pijnaker', 'DEF', 4),
    pl('NZL', 'Finn Surman', 'DEF', 5),
    pl('NZL', 'Liberato Cacace', 'DEF', 16),
    pl('NZL', 'Tyler Bindon', 'DEF', 22),
    pl('NZL', 'Francis de Vries', 'DEF', 13),
    pl('NZL', 'Joe Bell', 'MED', 6),
    pl('NZL', 'Marko Stamenic', 'MED', 8),
    pl('NZL', 'Matthew Garbett', 'MED', 17),
    pl('NZL', 'Alex Greive', 'MED', 14),
    pl('NZL', 'Clayton Lewis', 'MED', 15),
    pl('NZL', 'Ben Old', 'MED', 7),
    pl('NZL', 'Chris Wood', 'AVA', 9),
    pl('NZL', 'Kosta Barbarouses', 'AVA', 11),
    pl('NZL', 'Eli Just', 'AVA', 10),
    pl('NZL', 'Sarpreet Singh', 'AVA', 20),
    pl('NZL', 'Bill Tuiloma', 'AVA', 19),
  ],
  EGY: [
    pl('EGY', 'Mohamed El-Shenawy', 'GR', 1),
    pl('EGY', 'Mohamed Abou Gabal', 'GR', 16),
    pl('EGY', 'El Shenawy Sobhi', 'GR', 23),
    pl('EGY', 'Ahmed Hegazi', 'DEF', 4),
    pl('EGY', 'Mohamed Abdelmonem', 'DEF', 3),
    pl('EGY', 'Ahmed Fattouh', 'DEF', 12),
    pl('EGY', 'Omar Kamal', 'DEF', 2),
    pl('EGY', 'Mohamed Hany', 'DEF', 7),
    pl('EGY', 'Ahmed Hamdi', 'DEF', 13),
    pl('EGY', 'Rami Rabia', 'DEF', 6),
    pl('EGY', 'Mohamed Elneny', 'MED', 17),
    pl('EGY', 'Tarek Hamed', 'MED', 8),
    pl('EGY', 'Emam Ashour', 'MED', 14),
    pl('EGY', 'Mahmoud Trezeguet', 'MED', 21),
    pl('EGY', 'Mostafa Mohamed Fathy', 'MED', 15),
    pl('EGY', 'Nabil Emad Donga', 'MED', 18),
    pl('EGY', 'Mohamed Salah', 'AVA', 10),
    pl('EGY', 'Omar Marmoush', 'AVA', 9),
    pl('EGY', 'Mostafa Mohamed', 'AVA', 11),
    pl('EGY', 'Ramadan Sobhi', 'AVA', 20),
    pl('EGY', 'Ibrahim Adel', 'AVA', 19),
  ],
  AUT: [
    pl('AUT', 'Patrick Pentz', 'GR', 1),
    pl('AUT', 'Heinz Lindner', 'GR', 21),
    pl('AUT', 'Niklas Hedl', 'GR', 23),
    pl('AUT', 'David Alaba', 'DEF', 8),
    pl('AUT', 'Kevin Danso', 'DEF', 4),
    pl('AUT', 'Philipp Lienhart', 'DEF', 5),
    pl('AUT', 'Maximilian Wöber', 'DEF', 3),
    pl('AUT', 'Stefan Posch', 'DEF', 15),
    pl('AUT', 'Phillipp Mwene', 'DEF', 2),
    pl('AUT', 'Flavius Daniliuc', 'DEF', 16),
    pl('AUT', 'Konrad Laimer', 'MED', 6),
    pl('AUT', 'Nicolas Seiwald', 'MED', 13),
    pl('AUT', 'Florian Grillitsch', 'MED', 22),
    pl('AUT', 'Christoph Baumgartner', 'MED', 19),
    pl('AUT', 'Marcel Sabitzer', 'MED', 7),
    pl('AUT', 'Romano Schmid', 'MED', 14),
    pl('AUT', 'Marko Arnautović', 'AVA', 9),
    pl('AUT', 'Michael Gregoritsch', 'AVA', 11),
    pl('AUT', 'Patrick Wimmer', 'AVA', 18),
    pl('AUT', 'Maximilian Entrup', 'AVA', 20),
    pl('AUT', 'Marco Grüll', 'AVA', 17),
  ],
  IRQ: [
    pl('IRQ', 'Jalal Hassan', 'GR', 1),
    pl('IRQ', 'Fahad Talib', 'GR', 22),
    pl('IRQ', 'Ahmad Basil', 'GR', 23),
    pl('IRQ', 'Merchas Doski', 'DEF', 2),
    pl('IRQ', 'Rebin Sulaka', 'DEF', 3),
    pl('IRQ', 'Zaid Tahseen', 'DEF', 4),
    pl('IRQ', 'Akam Hashim', 'DEF', 5),
    pl('IRQ', 'Hussein Ali', 'DEF', 13),
    pl('IRQ', 'Mustafa Nadhim', 'DEF', 14),
    pl('IRQ', 'Frans Putros', 'DEF', 6),
    pl('IRQ', 'Amir Al-Ammari', 'MED', 8),
    pl('IRQ', 'Ibrahim Bayesh', 'MED', 17),
    pl('IRQ', 'Bashar Resan', 'MED', 7),
    pl('IRQ', 'Osama Rashid', 'MED', 18),
    pl('IRQ', 'Zidane Iqbal', 'MED', 15),
    pl('IRQ', 'Sajjad Jassim', 'MED', 16),
    pl('IRQ', 'Aymen Hussein', 'AVA', 9),
    pl('IRQ', 'Mohanad Ali', 'AVA', 10),
    pl('IRQ', 'Ali Jasim', 'AVA', 11),
    pl('IRQ', 'Manaf Younus', 'AVA', 19),
    pl('IRQ', 'Hussein Jwayed', 'AVA', 20),
  ],
  NOR: [
    pl('NOR', 'Ørjan Nyland', 'GR', 1),
    pl('NOR', 'Egil Selvik', 'GR', 12),
    pl('NOR', 'Mads Hedenstad', 'GR', 23),
    pl('NOR', 'Kristoffer Ajer', 'DEF', 2),
    pl('NOR', 'Leo Østigård', 'DEF', 5),
    pl('NOR', 'Stian Gregersen', 'DEF', 4),
    pl('NOR', 'David Møller Wolfe', 'DEF', 3),
    pl('NOR', 'Marcus Pedersen', 'DEF', 18),
    pl('NOR', 'Andreas Hanche-Olsen', 'DEF', 6),
    pl('NOR', 'Birger Meling', 'DEF', 16),
    pl('NOR', 'Martin Ødegaard', 'MED', 10),
    pl('NOR', 'Sander Berge', 'MED', 8),
    pl('NOR', 'Fredrik Aursnes', 'MED', 15),
    pl('NOR', 'Patrick Berg', 'MED', 13),
    pl('NOR', 'Morten Thorsby', 'MED', 14),
    pl('NOR', 'Antonio Nusa', 'MED', 7),
    pl('NOR', 'Erling Haaland', 'AVA', 9),
    pl('NOR', 'Alexander Sørloth', 'AVA', 11),
    pl('NOR', 'Oscar Bobb', 'AVA', 17),
    pl('NOR', 'Jørgen Strand Larsen', 'AVA', 20),
    pl('NOR', 'Mohamed Elyounoussi', 'AVA', 19),
  ],
  SEN: [
    pl('SEN', 'Édouard Mendy', 'GR', 16),
    pl('SEN', 'Seny Dieng', 'GR', 1),
    pl('SEN', 'Mory Diaw', 'GR', 23),
    pl('SEN', 'Kalidou Koulibaly', 'DEF', 3),
    pl('SEN', 'Abdou Diallo', 'DEF', 22),
    pl('SEN', 'Moussa Niakhaté', 'DEF', 21),
    pl('SEN', 'Ismail Jakobs', 'DEF', 12),
    pl('SEN', 'Krépin Diatta', 'DEF', 18),
    pl('SEN', 'Youssouf Sabaly', 'DEF', 2),
    pl('SEN', 'El Hadji Malick Diouf', 'DEF', 14),
    pl('SEN', 'Idrissa Gueye', 'MED', 5),
    pl('SEN', 'Pape Matar Sarr', 'MED', 17),
    pl('SEN', 'Pape Gueye', 'MED', 6),
    pl('SEN', 'Lamine Camara', 'MED', 13),
    pl('SEN', 'Pathé Ciss', 'MED', 15),
    pl('SEN', 'Sadio Mané', 'AVA', 10),
    pl('SEN', 'Ismaïla Sarr', 'AVA', 11),
    pl('SEN', 'Nicolas Jackson', 'AVA', 9),
    pl('SEN', 'Habib Diallo', 'AVA', 19),
    pl('SEN', 'Iliman Ndiaye', 'AVA', 7),
    pl('SEN', 'Boulaye Dia', 'AVA', 20),
  ],
  JOR: [
    pl('JOR', 'Yazeed Abulaila', 'GR', 1),
    pl('JOR', 'Abdullah Al-Fakhouri', 'GR', 22),
    pl('JOR', 'Ahmad Tawfeeq', 'GR', 23),
    pl('JOR', 'Salem Al-Ajalin', 'DEF', 2),
    pl('JOR', 'Yazan Al-Arab', 'DEF', 5),
    pl('JOR', 'Abdallah Nasib', 'DEF', 4),
    pl('JOR', 'Bara Marei', 'DEF', 3),
    pl('JOR', 'Ihsan Haddad', 'DEF', 13),
    pl('JOR', 'Mahmoud Al-Mardi', 'DEF', 14),
    pl('JOR', 'Feras Shelbaieh', 'DEF', 6),
    pl('JOR', 'Noor Al-Rawabdeh', 'MED', 7),
    pl('JOR', 'Nizar Al-Rashdan', 'MED', 8),
    pl('JOR', 'Ehsan Haddad', 'MED', 17),
    pl('JOR', 'Mahmoud Al-Mawas', 'MED', 18),
    pl('JOR', 'Rajaei Ayed', 'MED', 15),
    pl('JOR', 'Yazan Al-Naimat', 'AVA', 9),
    pl('JOR', 'Mousa Al-Taamari', 'AVA', 10),
    pl('JOR', 'Ali Olwan', 'AVA', 11),
    pl('JOR', 'Mohammad Abu Zrayq', 'AVA', 19),
    pl('JOR', 'Yazan Al-Arab II', 'AVA', 20),
    pl('JOR', 'Hamza Al-Dardour', 'AVA', 16),
  ],
  ALG: [
    pl('ALG', 'Anthony Mandrea', 'GR', 1),
    pl('ALG', 'Alexandre Oukidja', 'GR', 16),
    pl('ALG', 'Luca Zidane', 'GR', 23),
    pl('ALG', 'Aïssa Mandi', 'DEF', 4),
    pl('ALG', 'Ramy Bensebaini', 'DEF', 3),
    pl('ALG', 'Mohamed Amine Tougai', 'DEF', 5),
    pl('ALG', 'Youcef Atal', 'DEF', 2),
    pl('ALG', 'Jaouen Hadjam', 'DEF', 21),
    pl('ALG', 'Ahmed Touba', 'DEF', 22),
    pl('ALG', 'Mohamed Farsi', 'DEF', 12),
    pl('ALG', 'Ismaël Bennacer', 'MED', 6),
    pl('ALG', 'Nabil Bentaleb', 'MED', 13),
    pl('ALG', 'Ramiz Zerrouki', 'MED', 17),
    pl('ALG', 'Houssem Aouar', 'MED', 8),
    pl('ALG', 'Adem Zorgane', 'MED', 15),
    pl('ALG', 'Riyad Mahrez', 'AVA', 7),
    pl('ALG', 'Saïd Benrahma', 'AVA', 11),
    pl('ALG', 'Yacine Brahimi', 'AVA', 10),
    pl('ALG', 'Amine Gouiri', 'AVA', 9),
    pl('ALG', 'Mohamed Amoura', 'AVA', 18),
    pl('ALG', 'Baghdad Bounedjah', 'AVA', 20),
  ],
  UZB: [
    pl('UZB', 'Utkir Yusupov', 'GR', 1),
    pl('UZB', 'Abduvohid Nematov', 'GR', 12),
    pl('UZB', 'Vladimir Nazarov', 'GR', 23),
    pl('UZB', 'Rustamjon Ashurmatov', 'DEF', 4),
    pl('UZB', 'Abdukodir Khusanov', 'DEF', 5),
    pl('UZB', 'Farrukh Sayfiev', 'DEF', 2),
    pl('UZB', 'Sherzod Nasrullaev', 'DEF', 3),
    pl('UZB', 'Khojiakbar Alijonov', 'DEF', 13),
    pl('UZB', 'Umar Eshmurodov', 'DEF', 14),
    pl('UZB', 'Abbosbek Fayzullaev', 'MED', 10),
    pl('UZB', 'Jaloliddin Masharipov', 'MED', 7),
    pl('UZB', 'Otabek Shukurov', 'MED', 6),
    pl('UZB', 'Abdurauf Buriev', 'MED', 8),
    pl('UZB', 'Azizbek Turgunboev', 'MED', 17),
    pl('UZB', 'Jasurbek Jaloliddinov', 'MED', 15),
    pl('UZB', 'Oston Urunov', 'MED', 18),
    pl('UZB', 'Eldor Shomurodov', 'AVA', 9),
    pl('UZB', 'Igor Sergeev', 'AVA', 11),
    pl('UZB', 'Bobir Abdixolikov', 'AVA', 19),
    pl('UZB', 'Khojimat Erkinov', 'AVA', 20),
    pl('UZB', 'Sardor Mukhammadiev', 'AVA', 16),
  ],
  GHA: [
    pl('GHA', 'Lawrence Ati-Zigi', 'GR', 1),
    pl('GHA', 'Joseph Wollacott', 'GR', 12),
    pl('GHA', 'Benjamin Asare', 'GR', 23),
    pl('GHA', 'Alexander Djiku', 'DEF', 4),
    pl('GHA', 'Mohammed Salisu', 'DEF', 5),
    pl('GHA', 'Tariq Lamptey', 'DEF', 2),
    pl('GHA', 'Gideon Mensah', 'DEF', 3),
    pl('GHA', 'Alidu Seidu', 'DEF', 13),
    pl('GHA', 'Jerome Opoku', 'DEF', 14),
    pl('GHA', 'Denis Odoi', 'DEF', 6),
    pl('GHA', 'Thomas Partey', 'MED', 8),
    pl('GHA', 'Mohammed Kudus', 'MED', 20),
    pl('GHA', 'Elisha Owusu', 'MED', 17),
    pl('GHA', 'Salis Abdul Samed', 'MED', 15),
    pl('GHA', 'Majeed Ashimeru', 'MED', 18),
    pl('GHA', 'Ernest Nuamah', 'MED', 7),
    pl('GHA', 'Iñaki Williams', 'AVA', 9),
    pl('GHA', 'Jordan Ayew', 'AVA', 10),
    pl('GHA', 'Antoine Semenyo', 'AVA', 11),
    pl('GHA', 'Kamaldeen Sulemana', 'AVA', 19),
    pl('GHA', 'Abdul Fatawu Issahaku', 'AVA', 21),
  ],
  PAN: [
    pl('PAN', 'Orlando Mosquera', 'GR', 1),
    pl('PAN', 'José Guerra', 'GR', 12),
    pl('PAN', 'Luis Mejía', 'GR', 22),
    pl('PAN', 'Andrés Andrade', 'DEF', 20),
    pl('PAN', 'Fidel Escobar', 'DEF', 5),
    pl('PAN', 'César Blackman', 'DEF', 2),
    pl('PAN', 'Eric Davis', 'DEF', 15),
    pl('PAN', 'Michael Amir Murillo', 'DEF', 13),
    pl('PAN', 'Andrés Sánchez', 'DEF', 4),
    pl('PAN', 'Jose Córdoba', 'DEF', 3),
    pl('PAN', 'Aníbal Godoy', 'MED', 6),
    pl('PAN', 'Adalberto Carrasquilla', 'MED', 8),
    pl('PAN', 'Christian Martínez', 'MED', 17),
    pl('PAN', 'Edgardo Fariña', 'MED', 14),
    pl('PAN', 'Cristian Martínez II', 'MED', 16),
    pl('PAN', 'Ismael Díaz', 'AVA', 7),
    pl('PAN', 'José Fajardo', 'AVA', 9),
    pl('PAN', 'Cecilio Waterman', 'AVA', 11),
    pl('PAN', 'Eduardo Guerrero', 'AVA', 10),
    pl('PAN', 'Tomás Rodríguez', 'AVA', 19),
    pl('PAN', 'Azarías Londoño', 'AVA', 18),
  ],
  COL: [
    pl('COL', 'Camilo Vargas', 'GR', 1),
    pl('COL', 'David Ospina', 'GR', 12),
    pl('COL', 'Álvaro Montero', 'GR', 22),
    pl('COL', 'Daniel Muñoz', 'DEF', 4),
    pl('COL', 'Carlos Cuesta', 'DEF', 2),
    pl('COL', 'Dávinson Sánchez', 'DEF', 23),
    pl('COL', 'Yerry Mina', 'DEF', 3),
    pl('COL', 'Johan Mojica', 'DEF', 17),
    pl('COL', 'Santiago Arias', 'DEF', 13),
    pl('COL', 'Jhon Lucumí', 'DEF', 5),
    pl('COL', 'Richard Ríos', 'MED', 15),
    pl('COL', 'Jefferson Lerma', 'MED', 16),
    pl('COL', 'Kevin Castaño', 'MED', 6),
    pl('COL', 'James Rodríguez', 'MED', 10),
    pl('COL', 'Juan Fernando Quintero', 'MED', 20),
    pl('COL', 'Jorge Carrascal', 'MED', 8),
    pl('COL', 'Luis Díaz', 'AVA', 7),
    pl('COL', 'Jhon Durán', 'AVA', 9),
    pl('COL', 'Rafael Santos Borré', 'AVA', 11),
    pl('COL', 'Daniel Ruiz', 'AVA', 14),
    pl('COL', 'Luis Sinisterra', 'AVA', 19),
  ],
  COD: [
    pl('COD', 'Lionel Mpasi', 'GR', 1),
    pl('COD', 'Timothy Fayulu', 'GR', 16),
    pl('COD', 'Dimitry Bertaud', 'GR', 23),
    pl('COD', 'Chancel Mbemba', 'DEF', 4),
    pl('COD', 'Gédéon Kalulu', 'DEF', 2),
    pl('COD', 'Arthur Masuaku', 'DEF', 3),
    pl('COD', 'Axel Tuanzebe', 'DEF', 5),
    pl('COD', 'Rocky Bushiri', 'DEF', 13),
    pl('COD', 'Joris Kayembe', 'DEF', 14),
    pl('COD', 'Aaron Wan-Bissaka', 'DEF', 6),
    pl('COD', 'Charles Pickel', 'MED', 8),
    pl('COD', 'Samuel Moutoussamy', 'MED', 17),
    pl('COD', 'Edo Kayembe', 'MED', 7),
    pl('COD', 'Aaron Tshibola', 'MED', 15),
    pl('COD', 'Noah Sadiki', 'MED', 18),
    pl('COD', 'Théo Bongonda', 'AVA', 11),
    pl('COD', 'Cédric Bakambu', 'AVA', 9),
    pl('COD', 'Yoane Wissa', 'AVA', 10),
    pl('COD', 'Silas Katompa', 'AVA', 20),
    pl('COD', 'Meschack Elia', 'AVA', 19),
    pl('COD', 'Fiston Mayele', 'AVA', 21),
  ],
};
